import type { EvidenceReference, FilingAnalysis } from '@contracts/analysis';
type Lang='en'|'pt'; type Entry={name:string;data:Uint8Array}; const enc=new TextEncoder(); const EMU=914400; const SW=13.333,SH=7.5;
const C={bg:'0B0F1C',panel:'121A2C',cyan:'22D3EE',white:'F8FAFC',muted:'94A3B8',dim:'64748B',border:'26344F',green:'34D399',amber:'FBBF24',red:'FB7185'};
const esc=(v:unknown)=>String(v??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;'); const emu=(v:number)=>Math.round(v*EMU); const xml=(s:string)=>enc.encode(s);
function crc32(data:Uint8Array){let crc=0xffffffff;for(const byte of data){crc^=byte;for(let k=0;k<8;k++)crc=(crc>>>1)^(0xedb88320&-(crc&1));}return(crc^0xffffffff)>>>0} const u16=(v:number)=>new Uint8Array([v&255,(v>>>8)&255]); const u32=(v:number)=>new Uint8Array([v&255,(v>>>8)&255,(v>>>16)&255,(v>>>24)&255]);
function concat(parts:Uint8Array[]){const out=new Uint8Array(parts.reduce((s,p)=>s+p.length,0));let o=0;for(const p of parts){out.set(p,o);o+=p.length}return out}
function zip(entries:Entry[]){const locals:Uint8Array[]=[],centrals:Uint8Array[]=[];let offset=0;for(const e of entries){const name=enc.encode(e.name),crc=crc32(e.data);const local=concat([u32(0x04034b50),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(e.data.length),u32(e.data.length),u16(name.length),u16(0),name,e.data]);locals.push(local);centrals.push(concat([u32(0x02014b50),u16(20),u16(20),u16(0),u16(0),u16(0),u16(0),u32(crc),u32(e.data.length),u32(e.data.length),u16(name.length),u16(0),u16(0),u16(0),u16(0),u32(0),u32(offset),name]));offset+=local.length}const cs=centrals.reduce((s,p)=>s+p.length,0);return concat([...locals,...centrals,u32(0x06054b50),u16(0),u16(0),u16(entries.length),u16(entries.length),u32(cs),u32(offset),u16(0)])}
type Builder={shapes:string[];id:number}; const builder=():Builder=>({shapes:[],id:2});
function shape(b:Builder,x:number,y:number,w:number,h:number,fill?:string,body=''){const id=b.id++;b.shapes.push(`<p:sp><p:nvSpPr><p:cNvPr id="${id}" name="Shape ${id}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr><p:spPr><a:xfrm><a:off x="${emu(x)}" y="${emu(y)}"/><a:ext cx="${emu(w)}" cy="${emu(h)}"/></a:xfrm><a:prstGeom prst="roundRect"><a:avLst/></a:prstGeom>${fill?`<a:solidFill><a:srgbClr val="${fill}"/></a:solidFill>`:'<a:noFill/>'}<a:ln><a:noFill/></a:ln></p:spPr>${body}</p:sp>`)}
function text(b:Builder,value:string,x:number,y:number,w:number,h:number,size=14,color=C.white,bold=false,fill?:string){const paras=String(value||' ').split('\n').map(line=>`<a:p><a:pPr/><a:r><a:rPr lang="en-US" sz="${size*100}" b="${bold?1:0}"><a:solidFill><a:srgbClr val="${color}"/></a:solidFill><a:latin typeface="Aptos"/></a:rPr><a:t>${esc(line||' ')}</a:t></a:r><a:endParaRPr lang="en-US" sz="${size*100}"/></a:p>`).join('');shape(b,x,y,w,h,fill,`<p:txBody><a:bodyPr wrap="square" lIns="91440" rIns="91440" tIns="68580" bIns="68580"/><a:lstStyle/>${paras}</p:txBody>`)}
function title(b:Builder,value:string,sub:string,n:number,lang:Lang){text(b,value,.58,.32,11.7,.45,24,C.white,true);if(sub)text(b,sub,.6,.82,11.8,.34,10,C.muted);shape(b,.58,1.22,12.1,.035,C.cyan);text(b,lang==='pt'?'FilingLens · uso informativo':'FilingLens · informational use',.58,7.08,5,.2,8,C.dim);text(b,String(n),12.15,7.05,.5,.2,8,C.dim)}
function slide(b:Builder){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="${C.bg}"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>${b.shapes.join('')}</p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>`}
const fmt=(v:number|null|undefined,lang:Lang,s='')=>v==null||!Number.isFinite(v)?'—':`${new Intl.NumberFormat(lang==='pt'?'pt-BR':'en-US',{maximumFractionDigits:2}).format(v)}${s}`; const latest=(v?:number[]|null)=>v?.length?v.at(-1)??null:null; const trunc=(s:string,n:number)=>s.length>n?`${s.slice(0,n-1)}…`:s;
function src(s?:EvidenceReference|null){if(!s)return'';return s.url?`${s.publisher??'Web'}: ${s.url}`:[s.sourceForm,s.item,s.section,s.page?`p. ${s.page}`:null].filter(Boolean).join(' · ')}
function sources(d:FilingAnalysis){const out:string[]=[];const push=(s?:EvidenceReference|null)=>{const v=src(s);if(v&&!out.includes(v))out.push(v)};d.metadata.sources.forEach(push);d.kpis.forEach(x=>push(x.source));d.market.peerEvidence?.forEach(x=>push(x.source));d.risks.forEach(x=>push(x.source));d.financials.evidence?.forEach(x=>push(x.source));d.events.forEach(x=>push(x.source));return out.slice(0,16)}
function cards(b:Builder,items:Array<[string,string]>,y=1.55){items.slice(0,8).forEach(([a,v],i)=>{const col=i%4,row=Math.floor(i/4);const x=.6+col*3.12,yy=y+row*1.18;shape(b,x,yy,2.88,1,C.panel);text(b,a,x+.12,yy+.1,2.62,.22,9,C.muted,true);text(b,trunc(v,34),x+.12,yy+.38,2.62,.42,15,C.white,true)})}
function list(b:Builder,items:string[],x=.7,y=1.55,w=12,h=.62){items.slice(0,8).forEach((v,i)=>text(b,`• ${trunc(v,145)}`,x,y+i*h,w,h-.08,12,C.white,false,i%2?undefined:C.panel))}

export function buildCompanyPowerPointBytes(d:FilingAnalysis,lang:Lang):Uint8Array{const pt=lang==='pt',ss:string[]=[];const add=(b:Builder)=>ss.push(slide(b));
  {const b=builder();text(b,'FILINGLENS',.62,.38,2,.3,11,C.cyan,true);text(b,trunc(d.company.name||'Company',80),.62,1.55,11.8,1.1,31,C.white,true);text(b,pt?'Visão institucional e financeira':'Company & financial overview',.64,2.72,8,.4,17,C.muted);shape(b,.62,3.5,4.5,1.25,C.panel);text(b,`${d.metadata.filingType||d.company.filingType}\n${d.company.periodEnd||d.metadata.reportingPeriod||''}`,.86,3.78,4,.7,14,C.white,true);text(b,d.jurisdiction==='br'?'CVM · Brasil':'SEC · United States',.64,5.35,4,.3,12,C.cyan,true);text(b,pt?'Documento analisado + pesquisa web citável quando necessária.':'Analyzed filing + citable web research when needed.',.64,5.86,10,.4,11,C.muted);title(b,'','',1,lang);add(b)}
  {const b=builder();title(b,pt?'Resumo executivo':'Executive summary',pt?'Síntese das conclusões suportadas por evidência':'Evidence-supported synthesis',2,lang);list(b,d.summary.length?d.summary:[pt?'Resumo não disponível.':'Summary unavailable.']);add(b)}
  {const b=builder();title(b,pt?'Companhia em um relance':'Company snapshot',d.market.industry,3,lang);cards(b,d.kpis.slice(0,8).map(k=>[k.label,k.value]));text(b,trunc(d.company.description,420),.72,4.35,12,1.5,12,C.muted);add(b)}
  {const b=builder();title(b,pt?'Desempenho financeiro':'Financial performance',d.financials.unit,4,lang);cards(b,[['Revenue',fmt(latest(d.financials.revenue),lang)],['Net income',fmt(latest(d.financials.netIncome),lang)],['EBITDA',fmt(latest(d.financials.ebitda),lang)],['Cash',fmt(latest(d.financials.cash),lang)],['Total debt',fmt(latest(d.financials.totalDebt),lang)],['OCF',fmt(latest(d.financials.operatingCashFlow),lang)],['FCF',fmt(latest(d.financials.freeCashFlow),lang)],['Operating margin',fmt(latest(d.financials.operatingMargin),lang,'%')]]);text(b,(d.financials.years||[]).map((y,i)=>`${y}: Rev ${fmt(d.financials.revenue[i],lang)} · NI ${fmt(d.financials.netIncome[i],lang)}`).join('\n'),.72,4.25,12,1.65,11,C.muted,false,C.panel);add(b)}
  {const b=builder();title(b,pt?'Liquidez e alavancagem':'Liquidity & leverage',pt?'Indicadores reportados e calculados':'Reported and calculated indicators',5,lang);const m=d.financials.computed??[];cards(b,[['Net debt',fmt(latest(m.find(x=>x.key==='netDebt')?.values as number[]|undefined),lang)],['Net debt / EBITDA',fmt(latest(m.find(x=>x.key==='netDebtToEbitda')?.values as number[]|undefined),lang,'x')],['Current ratio',fmt(latest(m.find(x=>x.key==='currentRatio')?.values as number[]|undefined),lang,'x')],['Interest coverage',fmt(latest(m.find(x=>x.key==='interestCoverage')?.values as number[]|undefined),lang,'x')]]);list(b,(d.financials.validationFlags??[]).slice(0,5).map(x=>`${x.code}: ${x.note}`),.72,4.05,12,.5);add(b)}
  {const b=builder();title(b,pt?'Mercado e concorrentes':'Market & competitors',d.market.externalResearchStatus?`Research: ${d.market.externalResearchStatus}`:'',6,lang);const peers=(d.market.peerEvidence??[]).map(p=>`${p.name} [${p.sourceType==='external'?'WEB':'FILING'}]${p.source.url?` — ${p.source.url}`:''}`);list(b,peers.length?peers:[pt?'Nenhum par verificável.':'No verified peers.'],.72,1.55,12,.58);add(b)}
  {const b=builder();title(b,pt?'Mix operacional':'Operating mix',pt?'Segmentos e geografias divulgados':'Disclosed segments and geographies',7,lang);const items=[...d.market.segments.map(s=>`${s.name}: ${fmt(latest(s.revenue),lang)} (${(s.periods??d.financials.years).at(-1)??''})`),...d.market.geographies.map(g=>`${g.name}: ${fmt(latest(g.values),lang)} (${(g.periods??d.financials.years).at(-1)??''})`)];list(b,items.length?items:[pt?'Não divulgado.':'Not disclosed.']);add(b)}
  {const b=builder();title(b,pt?'Riscos principais':'Key risks',pt?'Ordenados por materialidade quando disponível':'Ranked by materiality when available',8,lang);list(b,[...d.risks].sort((a,b)=>(a.materialityRank??99)-(b.materialityRank??99)).map(r=>`${r.severity}/5 · ${r.category} · ${r.title}: ${r.summary}`));add(b)}
  {const b=builder();title(b,pt?'Linha do tempo e eventos':'Timeline & events',pt?'Eventos validados no documento':'Validated filing events',9,lang);list(b,d.events.map(e=>`${e.date} · ${e.category} · ${e.title}${e.impact?` — ${e.impact}`:''}`));add(b)}
  {const b=builder();title(b,pt?'Fontes, lacunas e metodologia':'Sources, gaps & methodology',pt?'Rastreabilidade da informação':'Information traceability',10,lang);const refs=sources(d);text(b,(pt?'FONTES\n':'SOURCES\n')+(refs.length?refs.map(x=>`• ${x}`).join('\n'):(pt?'• Documento enviado':'• Uploaded filing')),.7,1.5,7.7,4.9,9.5,C.white);text(b,(pt?'LACUNAS / NOTAS\n':'GAPS / NOTES\n')+(d.missingData.length?d.missingData.slice(0,8).map(x=>`• ${x}`).join('\n'):(pt?'• Nenhuma lacuna registrada':'• No recorded gaps')),.7+7.9,1.5,4.05,3.5,9.5,C.muted,false,C.panel);text(b,pt?'Metodologia: o deck usa o mesmo objeto validado do dashboard. Pesquisa web é separada e limitada a pares com URL citada.':'Methodology: the deck uses the same validated object as the dashboard. Web research is a separate peer-only stage and requires cited URLs.',8.6,5.25,4.05,1.05,9,C.cyan,false,C.panel);add(b)}
  const entries:Entry[]=[{name:'[Content_Types].xml',data:xml(contentTypes(ss.length))},{name:'_rels/.rels',data:xml(ROOT_RELS)},{name:'ppt/presentation.xml',data:xml(presentationXml(ss.length))},{name:'ppt/_rels/presentation.xml.rels',data:xml(presentationRels(ss.length))},{name:'ppt/slideMasters/slideMaster1.xml',data:xml(MASTER)},{name:'ppt/slideMasters/_rels/slideMaster1.xml.rels',data:xml(MASTER_RELS)},{name:'ppt/slideLayouts/slideLayout1.xml',data:xml(LAYOUT)},{name:'ppt/slideLayouts/_rels/slideLayout1.xml.rels',data:xml(LAYOUT_RELS)},{name:'ppt/theme/theme1.xml',data:xml(THEME)},{name:'docProps/app.xml',data:xml(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Properties xmlns="http://schemas.openxmlformats.org/officeDocument/2006/extended-properties"><Application>FilingLens</Application><Slides>${ss.length}</Slides></Properties>`)},{name:'docProps/core.xml',data:xml(`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:title>${esc(d.company.name)} — FilingLens</dc:title><dc:creator>FilingLens</dc:creator></cp:coreProperties>`)}];ss.forEach((s,i)=>{entries.push({name:`ppt/slides/slide${i+1}.xml`,data:xml(s)},{name:`ppt/slides/_rels/slide${i+1}.xml.rels`,data:xml(SLIDE_RELS)})});return zip(entries)}
function contentTypes(n:number){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/><Override PartName="/ppt/slideMasters/slideMaster1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideMaster+xml"/><Override PartName="/ppt/slideLayouts/slideLayout1.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slideLayout+xml"/><Override PartName="/ppt/theme/theme1.xml" ContentType="application/vnd.openxmlformats-officedocument.theme+xml"/><Override PartName="/docProps/core.xml" ContentType="application/vnd.openxmlformats-package.core-properties+xml"/><Override PartName="/docProps/app.xml" ContentType="application/vnd.openxmlformats-officedocument.extended-properties+xml"/>${Array.from({length:n},(_,i)=>`<Override PartName="/ppt/slides/slide${i+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>`).join('')}</Types>`}
function presentationXml(n:number){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:sldMasterIdLst><p:sldMasterId id="2147483648" r:id="rId1"/></p:sldMasterIdLst><p:sldIdLst>${Array.from({length:n},(_,i)=>`<p:sldId id="${256+i}" r:id="rId${i+2}"/>`).join('')}</p:sldIdLst><p:sldSz cx="${emu(SW)}" cy="${emu(SH)}" type="screen16x9"/><p:notesSz cx="6858000" cy="9144000"/><p:defaultTextStyle/></p:presentation>`}
function presentationRels(n:number){return `<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="slideMasters/slideMaster1.xml"/>${Array.from({length:n},(_,i)=>`<Relationship Id="rId${i+2}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide${i+1}.xml"/>`).join('')}</Relationships>`}
const ROOT_RELS=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/package/2006/relationships/metadata/core-properties" Target="docProps/core.xml"/><Relationship Id="rId3" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/extended-properties" Target="docProps/app.xml"/></Relationships>`;
const SLIDE_RELS=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/></Relationships>`;
const LAYOUT_RELS=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideMaster" Target="../slideMasters/slideMaster1.xml"/></Relationships>`;
const MASTER_RELS=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slideLayout" Target="../slideLayouts/slideLayout1.xml"/><Relationship Id="rId2" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/theme" Target="../theme/theme1.xml"/></Relationships>`;
const LAYOUT=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldLayout xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main" type="blank" preserve="1"><p:cSld name="Blank"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sldLayout>`;
const MASTER=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><p:sldMaster xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"><p:cSld name="FilingLens"><p:spTree><p:nvGrpSpPr><p:cNvPr id="1" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr><p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree></p:cSld><p:clrMap accent1="accent1" accent2="accent2" accent3="accent3" accent4="accent4" accent5="accent5" accent6="accent6" bg1="lt1" bg2="lt2" folHlink="folHlink" hlink="hlink" tx1="dk1" tx2="dk2"/><p:sldLayoutIdLst><p:sldLayoutId id="1" r:id="rId1"/></p:sldLayoutIdLst><p:txStyles><p:titleStyle/><p:bodyStyle/><p:otherStyle/></p:txStyles></p:sldMaster>`;
const THEME=`<?xml version="1.0" encoding="UTF-8" standalone="yes"?><a:theme xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" name="FilingLens"><a:themeElements><a:clrScheme name="FilingLens"><a:dk1><a:srgbClr val="0B0F1C"/></a:dk1><a:lt1><a:srgbClr val="F8FAFC"/></a:lt1><a:dk2><a:srgbClr val="121A2C"/></a:dk2><a:lt2><a:srgbClr val="E2E8F0"/></a:lt2><a:accent1><a:srgbClr val="22D3EE"/></a:accent1><a:accent2><a:srgbClr val="3B82F6"/></a:accent2><a:accent3><a:srgbClr val="34D399"/></a:accent3><a:accent4><a:srgbClr val="FBBF24"/></a:accent4><a:accent5><a:srgbClr val="FB7185"/></a:accent5><a:accent6><a:srgbClr val="94A3B8"/></a:accent6><a:hlink><a:srgbClr val="22D3EE"/></a:hlink><a:folHlink><a:srgbClr val="818CF8"/></a:folHlink></a:clrScheme><a:fontScheme name="FilingLens"><a:majorFont><a:latin typeface="Aptos Display"/><a:ea typeface=""/><a:cs typeface=""/></a:majorFont><a:minorFont><a:latin typeface="Aptos"/><a:ea typeface=""/><a:cs typeface=""/></a:minorFont></a:fontScheme><a:fmtScheme name="FilingLens"><a:fillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:fillStyleLst><a:lnStyleLst><a:ln w="6350"><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:ln></a:lnStyleLst><a:effectStyleLst><a:effectStyle><a:effectLst/></a:effectStyle></a:effectStyleLst><a:bgFillStyleLst><a:solidFill><a:schemeClr val="phClr"/></a:solidFill></a:bgFillStyleLst></a:fmtScheme></a:themeElements></a:theme>`;
export function downloadCompanyPowerPoint(data:FilingAnalysis,lang:Lang){const bytes=buildCompanyPowerPointBytes(data,lang);const blob=new Blob([new Uint8Array(bytes).buffer],{type:'application/vnd.openxmlformats-officedocument.presentationml.presentation'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${(data.company.name||'company').replace(/[^a-z0-9]+/gi,'-').replace(/^-|-$/g,'') || 'company'}-FilingLens.pptx`;a.click();URL.revokeObjectURL(a.href)}
