from __future__ import annotations

from io import BytesIO
from typing import Any

from pptx import Presentation
from pptx.chart.data import ChartData
from pptx.dml.color import RGBColor
from pptx.enum.chart import XL_CHART_TYPE, XL_LEGEND_POSITION
from pptx.enum.shapes import MSO_SHAPE
from pptx.enum.text import PP_ALIGN, MSO_ANCHOR
from pptx.util import Inches, Pt

BG = RGBColor(8, 16, 29)
PANEL = RGBColor(17, 28, 48)
PANEL_2 = RGBColor(12, 22, 40)
BORDER = RGBColor(43, 59, 86)
WHITE = RGBColor(248, 250, 252)
MUTED = RGBColor(148, 163, 184)
CYAN = RGBColor(34, 211, 238)
BLUE = RGBColor(96, 165, 250)
GREEN = RGBColor(52, 211, 153)
AMBER = RGBColor(251, 191, 36)
ROSE = RGBColor(251, 113, 133)
VIOLET = RGBColor(167, 139, 250)
FONT = "Aptos"

TEXT = {
    "en": {
        "brand": "FILINGLENS · COMPANY INTELLIGENCE",
        "cover_message": "Decision-ready filing intelligence",
        "cover_fallback": "Regulatory filing analysis with authoritative structured-data cross-checks, source provenance, risk context, and financial validation.",
        "disclaimer": "Informational use only · filing-first · source-aware · generated by FilingLens",
        "source_footer": "Source: uploaded filing bundle and validated regulatory data.",
        "overview_kicker": "Executive overview", "overview_title": "What matters from this filing", "takeaways": "KEY TAKEAWAYS",
        "no_summary": "No supported executive summary was produced.", "snapshot": "FILING SNAPSHOT",
        "jurisdiction": "Jurisdiction", "filing": "Filing", "reporting_period": "Reporting period", "structured_source": "Structured source", "data_status": "Data status",
        "financial_kicker": "Financial snapshot", "financial_title": "Latest reported metrics", "revenue": "Revenue", "net_income": "Net income", "ocf": "Operating cash flow", "cash": "Cash", "debt": "Total debt",
        "latest_reported": "latest reported", "balance_sheet": "balance sheet", "evidence_discipline": "Evidence discipline",
        "evidence_1": "Regulatory structured data is an authoritative cross-check, not an invisible overwrite.",
        "evidence_2": "Uploaded filing evidence remains primary for narrative, risk and management-context interpretation.",
        "evidence_3": "Conflicts and missing fields remain visible instead of being silently reconciled by the model.",
        "performance_kicker": "Financial performance", "performance_title": "Five-year scale, earnings and trajectory",
        "history_source": "Authoritative annual history",
        "competitive_kicker": "Competitive landscape", "competitive_title": "How the issuer is positioned against direct peers",
        "competitive_findings": "DECISION-USEFUL FINDINGS", "no_competitive": "No independently cited competitive analysis was available.",
        "cashflow_kicker": "Balance sheet & cash conversion", "cashflow_title": "Liquidity, leverage and cash generation", "cashflow_profile": "Cash flow profile", "capex": "Capex", "assets_equity": "Assets / Equity", "capital_structure": "capital structure", "latest_balance": "latest balance",
        "market_kicker": "Market & operating context", "market_title": "Where the company competes", "industry": "INDUSTRY", "peers": "VERIFIED PEERS", "segments": "OPERATING SEGMENTS", "geographies": "GEOGRAPHIES",
        "no_industry": "Not established from validated evidence", "no_peers": "No verified peers available", "no_segments": "No validated segment series", "no_geographies": "No validated geographic series",
        "risk_kicker": "Principal risk factors", "risk_title": "Material risks disclosed in the filing", "risk": "Risk", "no_risks": "No structured risk factors were captured.",
        "events_kicker": "Timeline & material events", "events_title": "Validated chronology", "event": "Event", "no_events": "No validated events were captured.",
        "quality_kicker": "Data quality & controls", "quality_title": "What is complete, partial or unavailable", "no_warnings": "No additional material data-quality warnings were reported.",
        "sources_kicker": "Sources & methodology", "sources_title": "Evidence hierarchy and presentation controls", "source_hierarchy": "SOURCE HIERARCHY", "pptx_qa": "POWERPOINT QA",
        "hierarchy_1": "1. SEC EDGAR / CVM structured regulatory data", "hierarchy_2": "2. Uploaded regulatory filing bundle", "hierarchy_3": "3. Optional citation-backed external research", "hierarchy_4": "4. Derived metrics only when formulas and components are explicit",
        "qa_1": "Generated server-side with python-pptx rather than handcrafted browser OOXML.", "qa_2": "Saved to a byte stream and reopened by python-pptx before delivery.", "qa_3": "Slide count, package readability and source provenance are checked deterministically.", "qa_4": "Microsoft PowerPoint rendering should still be visually reviewed before consequential distribution.",
        "method_footer": "Method: filing-first extraction + authoritative structured-data cross-check + bounded specialist synthesis.",
        "no_series": "No comparable series available",
    },
    "pt": {
        "brand": "FILINGLENS · INTELIGÊNCIA DE COMPANHIAS",
        "cover_message": "Inteligência de filings pronta para decisão",
        "cover_fallback": "Análise regulatória com cruzamento de dados estruturados oficiais, proveniência, contexto de riscos e validação financeira.",
        "disclaimer": "Uso informacional · filing-first · fontes explícitas · gerado pelo FilingLens",
        "source_footer": "Fonte: conjunto de filings enviado e dados regulatórios validados.",
        "overview_kicker": "Visão executiva", "overview_title": "O que mais importa neste filing", "takeaways": "PRINCIPAIS CONCLUSÕES",
        "no_summary": "Nenhum resumo executivo suportado por evidências foi produzido.", "snapshot": "RESUMO DO FILING",
        "jurisdiction": "Jurisdição", "filing": "Documento", "reporting_period": "Período", "structured_source": "Fonte estruturada", "data_status": "Status dos dados",
        "financial_kicker": "Resumo financeiro", "financial_title": "Principais métricas reportadas", "revenue": "Receita", "net_income": "Lucro líquido", "ocf": "Fluxo de caixa operacional", "cash": "Caixa", "debt": "Dívida total",
        "latest_reported": "último período", "balance_sheet": "balanço", "evidence_discipline": "Disciplina de evidências",
        "evidence_1": "Dados regulatórios estruturados funcionam como verificação oficial, não como sobrescrita invisível.",
        "evidence_2": "O filing enviado permanece como fonte primária para narrativa, riscos e contexto gerencial.",
        "evidence_3": "Conflitos e lacunas permanecem visíveis em vez de serem reconciliados silenciosamente pelo modelo.",
        "performance_kicker": "Desempenho financeiro", "performance_title": "Cinco anos de escala, resultado e trajetória",
        "history_source": "Histórico anual regulatório oficial",
        "competitive_kicker": "Cenário competitivo", "competitive_title": "Como a companhia se posiciona frente aos pares diretos",
        "competitive_findings": "CONCLUSÕES ÚTEIS PARA DECISÃO", "no_competitive": "Não havia análise competitiva independente com citações verificadas.",
        "cashflow_kicker": "Balanço e conversão de caixa", "cashflow_title": "Liquidez, alavancagem e geração de caixa", "cashflow_profile": "Perfil de fluxo de caixa", "capex": "Capex", "assets_equity": "Ativos / Patrimônio", "capital_structure": "estrutura de capital", "latest_balance": "último saldo",
        "market_kicker": "Mercado e operação", "market_title": "Onde a companhia compete", "industry": "INDÚSTRIA", "peers": "PARES VERIFICADOS", "segments": "SEGMENTOS OPERACIONAIS", "geographies": "GEOGRAFIAS",
        "no_industry": "Não estabelecido por evidência validada", "no_peers": "Nenhum par verificado disponível", "no_segments": "Nenhuma série de segmentos validada", "no_geographies": "Nenhuma série geográfica validada",
        "risk_kicker": "Principais fatores de risco", "risk_title": "Riscos materiais divulgados no filing", "risk": "Risco", "no_risks": "Nenhum fator de risco estruturado foi capturado.",
        "events_kicker": "Linha do tempo e eventos materiais", "events_title": "Cronologia validada", "event": "Evento", "no_events": "Nenhum evento validado foi capturado.",
        "quality_kicker": "Qualidade dos dados e controles", "quality_title": "O que está completo, parcial ou indisponível", "no_warnings": "Nenhum alerta material adicional de qualidade dos dados foi reportado.",
        "sources_kicker": "Fontes e metodologia", "sources_title": "Hierarquia de evidências e controles da apresentação", "source_hierarchy": "HIERARQUIA DE FONTES", "pptx_qa": "QA DO POWERPOINT",
        "hierarchy_1": "1. Dados regulatórios estruturados SEC EDGAR / CVM", "hierarchy_2": "2. Conjunto de filings regulatórios enviado", "hierarchy_3": "3. Pesquisa externa opcional com citações", "hierarchy_4": "4. Métricas derivadas apenas com fórmulas e componentes explícitos",
        "qa_1": "Gerado no servidor com python-pptx, sem OOXML artesanal no navegador.", "qa_2": "Salvo em memória e reaberto pelo python-pptx antes da entrega.", "qa_3": "Quantidade de slides, legibilidade do pacote e proveniência são verificadas deterministicamente.", "qa_4": "A renderização no Microsoft PowerPoint ainda deve ser revisada visualmente antes de distribuição relevante.",
        "method_footer": "Método: extração filing-first + verificação regulatória estruturada + síntese especializada limitada.",
        "no_series": "Nenhuma série comparável disponível",
    },
}


def _clean(value: Any, fallback: str = "—") -> str:
    if value is None or value == "":
        return fallback
    return str(value)


def _series_latest(values: Any) -> float | None:
    if not isinstance(values, list):
        return None
    for value in reversed(values):
        if isinstance(value, (int, float)):
            return float(value)
    return None


def _unit_multiplier(unit: str | None) -> float:
    text = (unit or "").lower().replace("õ", "o").replace("ó", "o")
    if "billion" in text or "bilhao" in text or "bilhoes" in text:
        return 1_000_000_000.0
    if "million" in text or "milhao" in text or "milhoes" in text:
        return 1_000_000.0
    if "thousand" in text or "milhares" in text:
        return 1_000.0
    return 1.0


def _money(value: float | None, jurisdiction: str, unit: str | None = None) -> str:
    if value is None:
        return "—"
    absolute_value = value * _unit_multiplier(unit)
    prefix = "R$" if jurisdiction == "br" else "$"
    magnitude = abs(absolute_value)
    if magnitude >= 1_000_000_000:
        return f"{prefix}{absolute_value / 1_000_000_000:,.1f}B"
    if magnitude >= 1_000_000:
        return f"{prefix}{absolute_value / 1_000_000:,.1f}M"
    if magnitude >= 1_000:
        return f"{prefix}{absolute_value / 1_000:,.1f}K"
    return f"{prefix}{absolute_value:,.1f}"


def _blank(prs: Presentation):
    slide = prs.slides.add_slide(prs.slide_layouts[6])
    bg = slide.background.fill
    bg.solid()
    bg.fore_color.rgb = BG
    return slide


def _textbox(slide, x, y, w, h, text, size=14, color=WHITE, bold=False, align=PP_ALIGN.LEFT, valign=MSO_ANCHOR.TOP):
    box = slide.shapes.add_textbox(Inches(x), Inches(y), Inches(w), Inches(h))
    tf = box.text_frame
    tf.clear()
    tf.word_wrap = True
    tf.vertical_anchor = valign
    p = tf.paragraphs[0]
    p.text = str(text)
    p.alignment = align
    r = p.runs[0]
    r.font.name = FONT
    r.font.size = Pt(size)
    r.font.bold = bold
    r.font.color.rgb = color
    return box


def _rect(slide, x, y, w, h, fill=PANEL, line=BORDER, radius=True):
    shape_type = MSO_SHAPE.ROUNDED_RECTANGLE if radius else MSO_SHAPE.RECTANGLE
    shp = slide.shapes.add_shape(shape_type, Inches(x), Inches(y), Inches(w), Inches(h))
    shp.fill.solid()
    shp.fill.fore_color.rgb = fill
    shp.line.color.rgb = line
    if radius:
        try:
            shp.adjustments[0] = 0.08
        except Exception:
            pass
    return shp


def _title(slide, kicker, title, page=None):
    rule = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, 0, 0, Inches(13.333), Inches(0.05))
    rule.fill.solid()
    rule.fill.fore_color.rgb = CYAN
    rule.line.fill.background()
    _textbox(slide, .65, .28, 11.6, .25, kicker.upper(), 8.5, CYAN, True)
    _textbox(slide, .65, .60, 11.9, .55, title, 25, WHITE, True)
    if page is not None:
        _textbox(slide, 12.1, .34, .55, .25, str(page), 8, MUTED, False, PP_ALIGN.RIGHT)


def _footer(slide, text):
    line = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(.65), Inches(7.04), Inches(12), Inches(.01))
    line.fill.solid()
    line.fill.fore_color.rgb = BORDER
    line.line.fill.background()
    _textbox(slide, .65, 7.08, 12, .18, text, 7, MUTED)


def _metric_card(slide, x, y, w, label, value, detail="", accent=CYAN):
    _rect(slide, x, y, w, 1.05, PANEL, BORDER)
    accent_shape = slide.shapes.add_shape(MSO_SHAPE.RECTANGLE, Inches(x), Inches(y), Inches(.05), Inches(1.05))
    accent_shape.fill.solid()
    accent_shape.fill.fore_color.rgb = accent
    accent_shape.line.fill.background()
    _textbox(slide, x + .18, y + .13, w - .30, .18, label.upper(), 7.5, MUTED, True)
    _textbox(slide, x + .18, y + .38, w - .30, .30, value, 18, WHITE, True)
    if detail:
        _textbox(slide, x + .18, y + .77, w - .30, .15, detail, 7, MUTED)


def _bullet_list(slide, items, x, y, w, max_items=5, color=WHITE, accent=CYAN, size=12):
    items = [str(i).strip() for i in (items or []) if str(i).strip()][:max_items]
    for idx, item in enumerate(items):
        top = y + idx * .67
        dot = slide.shapes.add_shape(MSO_SHAPE.OVAL, Inches(x), Inches(top + .12), Inches(.08), Inches(.08))
        dot.fill.solid()
        dot.fill.fore_color.rgb = accent
        dot.line.fill.background()
        _textbox(slide, x + .20, top, w - .20, .55, item, size, color)


def _add_chart(slide, x, y, w, h, title, categories, series, no_series, chart_type=XL_CHART_TYPE.COLUMN_CLUSTERED):
    _rect(slide, x, y, w, h, PANEL_2, BORDER)
    _textbox(slide, x + .20, y + .15, w - .4, .25, title, 11, WHITE, True)
    if not categories or not series:
        _textbox(slide, x + .3, y + 1.0, w - .6, .4, no_series, 10, MUTED, False, PP_ALIGN.CENTER)
        return
    normalized = []
    for name, values in series:
        if not isinstance(values, list) or len(values) != len(categories):
            continue
        normalized.append((name, [float(v) if isinstance(v, (int, float)) else None for v in values]))
    if not normalized:
        _textbox(slide, x + .3, y + 1.0, w - .6, .4, no_series, 10, MUTED, False, PP_ALIGN.CENTER)
        return
    data = ChartData()
    data.categories = [str(c) for c in categories]
    for name, values in normalized:
        data.add_series(name, values)
    chart = slide.shapes.add_chart(chart_type, Inches(x + .2), Inches(y + .55), Inches(w - .4), Inches(h - .75), data).chart
    chart.has_legend = len(normalized) > 1
    if chart.has_legend and chart.legend is not None:
        chart.legend.position = XL_LEGEND_POSITION.BOTTOM
        chart.legend.include_in_layout = False
    chart.has_title = False
    chart.value_axis.has_major_gridlines = True
    chart.value_axis.major_gridlines.format.line.color.rgb = BORDER
    chart.category_axis.tick_labels.font.name = FONT
    chart.category_axis.tick_labels.font.size = Pt(8)
    chart.category_axis.tick_labels.font.color.rgb = MUTED
    chart.value_axis.tick_labels.font.name = FONT
    chart.value_axis.tick_labels.font.size = Pt(8)
    chart.value_axis.tick_labels.font.color.rgb = MUTED
    palette = [CYAN, BLUE, GREEN, VIOLET, AMBER]
    for idx, series_item in enumerate(chart.series):
        series_item.format.fill.solid()
        series_item.format.fill.fore_color.rgb = palette[idx % len(palette)]
        series_item.format.line.color.rgb = palette[idx % len(palette)]


def _status_label(value: str, lang: str) -> str:
    if lang != "pt":
        return value.replace("_", " ").upper()
    return {
        "complete": "COMPLETO", "incomplete": "PARCIAL", "failed": "FALHOU",
        "not_applicable": "NÃO APLICÁVEL", "unknown": "DESCONHECIDO",
        "unavailable": "INDISPONÍVEL", "identifier_missing": "IDENTIFICADOR AUSENTE",
    }.get(value, value.replace("_", " ").upper())


def build_presentation(analysis: dict[str, Any], lang: str = "en") -> tuple[bytes, str]:
    lang = "pt" if lang == "pt" else "en"
    t = TEXT[lang]
    prs = Presentation()
    prs.slide_width = Inches(13.333333)
    prs.slide_height = Inches(7.5)
    while prs.slides:
        r_id = prs.slides._sldIdLst[0].rId
        prs.part.drop_rel(r_id)
        del prs.slides._sldIdLst[0]

    company = analysis.get("company") or {}
    financials = analysis.get("financials") or {}
    market = analysis.get("market") or {}
    risks = analysis.get("risks") or []
    events = analysis.get("events") or []
    summary = analysis.get("summary") or []
    diagnostics = analysis.get("diagnostics") or {}
    regulatory = analysis.get("regulatoryData") or {}
    annual_history = financials.get("annualHistory") or {}
    competitive = market.get("competitiveAnalysis") or {}
    jurisdiction = analysis.get("jurisdiction") or "us"
    unit = _clean(financials.get("unit"), "")
    name = _clean(company.get("name"), "Company")
    ticker = _clean(company.get("ticker"), "")
    form = _clean(company.get("filingType"), "Filing")
    period = _clean(company.get("periodEnd") or (analysis.get("metadata") or {}).get("reportingPeriod"), "")
    source_footer = t["source_footer"]

    s = _blank(prs)
    _textbox(s, .75, .55, 4.6, .3, t["brand"], 9, CYAN, True)
    _textbox(s, .75, 1.35, 11.4, .8, name, 34, WHITE, True)
    _textbox(s, .75, 2.20, 11.0, .45, f"{ticker + ' · ' if ticker else ''}{form} · {period}", 15, MUTED)
    _rect(s, .75, 3.25, 11.85, 2.35, PANEL, BORDER)
    _textbox(s, 1.05, 3.55, 11.15, .3, t["cover_message"], 17, WHITE, True)
    _textbox(s, 1.05, 4.05, 10.9, 1.15, company.get("description") or t["cover_fallback"], 13, MUTED)
    _textbox(s, .75, 6.65, 11.8, .2, t["disclaimer"], 8, MUTED)

    s = _blank(prs)
    _title(s, t["overview_kicker"], t["overview_title"], 2)
    _rect(s, .65, 1.35, 7.75, 5.2, PANEL, BORDER)
    _textbox(s, .9, 1.62, 7.2, .3, t["takeaways"], 9, CYAN, True)
    _bullet_list(s, summary or [t["no_summary"]], .95, 2.08, 7.05, 6, size=12)
    _rect(s, 8.65, 1.35, 4.05, 5.2, PANEL_2, BORDER)
    _textbox(s, 8.95, 1.62, 3.45, .3, t["snapshot"], 9, BLUE, True)
    snapshot = [
        (t["jurisdiction"], "CVM / Brasil" if jurisdiction == "br" and lang == "pt" else "CVM / Brazil" if jurisdiction == "br" else "SEC / Estados Unidos" if lang == "pt" else "SEC / United States"),
        (t["filing"], form),
        (t["reporting_period"], period),
        (t["structured_source"], regulatory.get("provider") or ("Não disponível" if lang == "pt" else "Not available")),
        (t["data_status"], _status_label(str(regulatory.get("status") or "filing-only"), lang)),
    ]
    for i, (key, value) in enumerate(snapshot):
        _textbox(s, 8.95, 2.10 + i * .70, 1.25, .18, key.upper(), 7, MUTED, True)
        _textbox(s, 10.20, 2.04 + i * .70, 2.15, .28, value, 10, WHITE, True)
    _footer(s, source_footer)

    years = financials.get("years") or []
    revenue = financials.get("revenue") or []
    net_income = financials.get("netIncome") or []
    ocf = financials.get("operatingCashFlow") or []
    cash = financials.get("cash") or []
    debt = financials.get("totalDebt") or []
    history_years = annual_history.get("years") or years
    history_revenue = annual_history.get("revenue") or revenue
    history_net_income = annual_history.get("netIncome") or net_income
    history_ocf = annual_history.get("operatingCashFlow") or ocf
    history_capex = annual_history.get("capex") or financials.get("capex") or []
    history_cash = annual_history.get("cash") or cash
    history_debt = annual_history.get("totalDebt") or debt
    history_assets = annual_history.get("totalAssets") or financials.get("totalAssets") or []
    history_equity = annual_history.get("totalEquity") or financials.get("totalEquity") or []
    history_unit = _clean(annual_history.get("unit"), unit)

    s = _blank(prs)
    _title(s, t["financial_kicker"], t["financial_title"], 3)
    cards = [
        (t["revenue"], _money(_series_latest(revenue), jurisdiction, unit), t["latest_reported"], CYAN),
        (t["net_income"], _money(_series_latest(net_income), jurisdiction, unit), t["latest_reported"], GREEN),
        (t["ocf"], _money(_series_latest(ocf), jurisdiction, unit), t["latest_reported"], BLUE),
        (t["cash"], _money(_series_latest(cash), jurisdiction, unit), t["balance_sheet"], VIOLET),
        (t["debt"], _money(_series_latest(debt), jurisdiction, unit), t["balance_sheet"], AMBER),
    ]
    for i, card in enumerate(cards):
        _metric_card(s, .65 + i * 2.42, 1.45, 2.18, *card)
    _rect(s, .65, 2.85, 12.0, 3.6, PANEL_2, BORDER)
    _textbox(s, .9, 3.10, 11.4, .25, t["evidence_discipline"], 12, WHITE, True)
    _bullet_list(s, [t["evidence_1"], t["evidence_2"], t["evidence_3"]], .95, 3.58, 11.1, 4, size=12, accent=GREEN)
    _footer(s, f"{source_footer} · {unit}" if unit else source_footer)

    s = _blank(prs)
    _title(s, t["performance_kicker"], t["performance_title"], 4)
    chart_unit = f" ({history_unit})" if history_unit else ""
    _add_chart(s, .65, 1.35, 6.0, 5.45, f"{t['revenue']}{chart_unit}", history_years, [(t["revenue"], history_revenue)], t["no_series"], XL_CHART_TYPE.COLUMN_CLUSTERED)
    _add_chart(s, 6.85, 1.35, 5.8, 5.45, f"{t['net_income']}{chart_unit}", history_years, [(t["net_income"], history_net_income)], t["no_series"], XL_CHART_TYPE.LINE_MARKERS)
    history_provider = annual_history.get("provider")
    history_footer = f"{t['history_source']}: {history_provider}" if history_provider else source_footer
    _footer(s, history_footer)

    s = _blank(prs)
    _title(s, t["cashflow_kicker"], t["cashflow_title"], 5)
    _add_chart(s, .65, 1.35, 7.25, 5.45, f"{t['cashflow_profile']}{chart_unit}", history_years, [(t["ocf"], history_ocf), (t["capex"], history_capex)], t["no_series"], XL_CHART_TYPE.COLUMN_CLUSTERED)
    _rect(s, 8.15, 1.35, 4.5, 5.45, PANEL, BORDER)
    _metric_card(s, 8.42, 1.72, 3.95, t["cash"], _money(_series_latest(history_cash), jurisdiction, history_unit), t["latest_balance"], GREEN)
    _metric_card(s, 8.42, 3.02, 3.95, t["debt"], _money(_series_latest(history_debt), jurisdiction, history_unit), t["latest_balance"], AMBER)
    assets = _series_latest(history_assets)
    equity = _series_latest(history_equity)
    _metric_card(s, 8.42, 4.32, 3.95, t["assets_equity"], f"{_money(assets, jurisdiction, history_unit)} / {_money(equity, jurisdiction, history_unit)}", t["capital_structure"], BLUE)
    _footer(s, history_footer)

    s = _blank(prs)
    _title(s, t["market_kicker"], t["market_title"], 6)
    _rect(s, .65, 1.35, 4.0, 5.45, PANEL, BORDER)
    _textbox(s, .9, 1.62, 3.5, .25, t["industry"], 9, CYAN, True)
    _textbox(s, .9, 2.00, 3.45, .7, market.get("industry") or t["no_industry"], 15, WHITE, True)
    _textbox(s, .9, 3.0, 3.5, .25, t["peers"], 9, BLUE, True)
    _bullet_list(s, market.get("competitors") or [t["no_peers"]], .95, 3.35, 3.4, 5, size=10.5, accent=BLUE)
    _rect(s, 4.90, 1.35, 3.75, 5.45, PANEL_2, BORDER)
    _textbox(s, 5.15, 1.62, 3.25, .25, t["segments"], 9, GREEN, True)
    segment_items = [x.get("name") for x in (market.get("segments") or []) if isinstance(x, dict) and x.get("name")]
    _bullet_list(s, segment_items or [t["no_segments"]], 5.2, 2.05, 3.1, 6, size=10.5, accent=GREEN)
    _rect(s, 8.90, 1.35, 3.75, 5.45, PANEL, BORDER)
    _textbox(s, 9.15, 1.62, 3.25, .25, t["geographies"], 9, VIOLET, True)
    geography_items = [x.get("name") for x in (market.get("geographies") or []) if isinstance(x, dict) and x.get("name")]
    _bullet_list(s, geography_items or [t["no_geographies"]], 9.2, 2.05, 3.1, 6, size=10.5, accent=VIOLET)
    _footer(s, source_footer)

    s = _blank(prs)
    _title(s, t["competitive_kicker"], t["competitive_title"], 7)
    peer_profiles = competitive.get("peerProfiles") or []
    findings = competitive.get("findings") or []
    market_structure = competitive.get("marketStructure") or {}
    _rect(s, .65, 1.35, 6.1, 5.45, PANEL, BORDER)
    _textbox(s, .92, 1.62, 5.55, .25, t["peers"], 9, CYAN, True)
    if peer_profiles:
        for i, peer in enumerate(peer_profiles[:5]):
            y = 2.02 + i * .86
            _textbox(s, .95, y, 1.55, .25, _clean(peer.get("name"), "Peer"), 10.5, WHITE, True)
            _textbox(s, 2.45, y, 3.95, .48, _clean(peer.get("positioning"), ""), 8.5, MUTED)
    else:
        _textbox(s, .95, 2.05, 5.45, .4, t["no_competitive"], 10.5, MUTED)
    _rect(s, 7.0, 1.35, 5.65, 5.45, PANEL_2, BORDER)
    _textbox(s, 7.28, 1.62, 5.05, .25, t["competitive_findings"], 9, GREEN, True)
    if market_structure:
        _textbox(s, 7.28, 2.00, 5.0, .70, _clean(market_structure.get("summary"), ""), 10.5, WHITE, True)
    finding_items = []
    for item in findings[:4]:
        if isinstance(item, dict):
            finding_items.append(f"{_clean(item.get('insight'), '')} — {_clean(item.get('implication'), '')}")
    _bullet_list(s, finding_items or [t["no_competitive"]], 7.3, 2.85, 4.95, 4, size=9.8, accent=GREEN)
    _footer(s, t["hierarchy_3"])

    s = _blank(prs)
    _title(s, t["risk_kicker"], t["risk_title"], 8)
    risk_items = []
    for item in risks[:6]:
        if isinstance(item, dict):
            risk_items.append(f"{item.get('title', t['risk'])} — {item.get('summary', '')}")
    _rect(s, .65, 1.35, 12.0, 5.45, PANEL, BORDER)
    _bullet_list(s, risk_items or [t["no_risks"]], .95, 1.75, 11.35, 6, size=11.5, accent=ROSE)
    _footer(s, source_footer)

    s = _blank(prs)
    _title(s, t["events_kicker"], t["events_title"], 9)
    _rect(s, .65, 1.35, 12.0, 5.45, PANEL_2, BORDER)
    if events:
        for i, item in enumerate(events[:7]):
            date = _clean(item.get("date"), "") if isinstance(item, dict) else ""
            title = _clean(item.get("title"), t["event"]) if isinstance(item, dict) else str(item)
            impact = _clean(item.get("impact"), "") if isinstance(item, dict) else ""
            _textbox(s, .95, 1.72 + i * .67, 1.15, .25, date, 9, CYAN, True)
            _textbox(s, 2.05, 1.67 + i * .67, 3.5, .30, title, 11, WHITE, True)
            _textbox(s, 5.55, 1.67 + i * .67, 6.55, .42, impact, 9.5, MUTED)
    else:
        _textbox(s, .95, 2.1, 11.3, .4, t["no_events"], 12, MUTED, False, PP_ALIGN.CENTER)
    _footer(s, source_footer)

    s = _blank(prs)
    _title(s, t["quality_kicker"], t["quality_title"], 10)
    module_names = ["metadata", "profiler", "financials", "market", "risks", "historian", "synthesizer"]
    for i, module in enumerate(module_names):
        diagnostic = diagnostics.get(module) or {}
        status = str(diagnostic.get("status") or "unknown")
        accent = GREEN if status in ("complete", "not_applicable") else AMBER if status == "incomplete" else ROSE
        x = .65 + (i % 4) * 3.0
        y = 1.45 + (i // 4) * 1.50
        _rect(s, x, y, 2.75, 1.15, PANEL, BORDER)
        _textbox(s, x + .18, y + .18, 2.25, .22, module.upper(), 8, MUTED, True)
        _textbox(s, x + .18, y + .48, 2.25, .28, _status_label(status, lang), 12, accent, True)
        if diagnostic.get("reason"):
            _textbox(s, x + .18, y + .80, 2.25, .22, str(diagnostic.get("reason")).replace("_", " "), 7.5, MUTED)
    _rect(s, .65, 4.65, 12.0, 1.80, PANEL_2, BORDER)
    warnings = list(regulatory.get("warnings") or []) + list(analysis.get("missingData") or [])
    _bullet_list(s, warnings or [t["no_warnings"]], .95, 4.95, 11.3, 3, size=10.5, accent=AMBER)
    _footer(s, source_footer)

    s = _blank(prs)
    _title(s, t["sources_kicker"], t["sources_title"], 11)
    _rect(s, .65, 1.35, 5.85, 5.45, PANEL, BORDER)
    _textbox(s, .95, 1.68, 5.2, .25, t["source_hierarchy"], 9, CYAN, True)
    hierarchy = [t["hierarchy_1"], t["hierarchy_2"], t["hierarchy_3"], t["hierarchy_4"]]
    _bullet_list(s, hierarchy, 1.0, 2.05, 5.0, 5, size=11, accent=CYAN)
    _rect(s, 6.75, 1.35, 5.90, 5.45, PANEL_2, BORDER)
    _textbox(s, 7.05, 1.68, 5.3, .25, t["pptx_qa"], 9, GREEN, True)
    qa = [t["qa_1"], t["qa_2"], t["qa_3"], t["qa_4"]]
    _bullet_list(s, qa, 7.1, 2.05, 5.1, 5, size=10.8, accent=GREEN)
    _footer(s, t["method_footer"])

    out = BytesIO()
    prs.save(out)
    raw = out.getvalue()
    reopened = Presentation(BytesIO(raw))
    if len(reopened.slides) != len(prs.slides) or len(raw) < 5000 or raw[:2] != b"PK":
        raise RuntimeError("pptx_roundtrip_validation_failed")
    safe = "".join(ch if ch.isalnum() or ch in "-_" else "-" for ch in name).strip("-") or "company"
    return raw, f"{safe}-FilingLens-Analysis.pptx"
