import { useEffect, useMemo, useState } from 'react';
import Dashboard from '@/components/Dashboard';
import { downloadCompanyPowerPoint } from '@/lib/powerpoint';
import type { AgentName, FilingAnalysis, FilingClassification, Market, ModuleDiagnostic } from '@contracts/analysis';

const AGENTS: AgentName[] = ['profiler','market','risks','financials','historian','synthesizer'];
type Lang = 'en' | 'pt';
type Status = 'pending'|'running'|'complete'|'partial'|'failed'|'skipped';
type StageKey = 'extract'|'metadata'|AgentName|'market-research'|'dashboard';
const STAGES: StageKey[] = ['extract','metadata','profiler','market','market-research','risks','financials','historian','synthesizer','dashboard'];
const LABELS: Record<StageKey,{en:string;pt:string}> = {
  extract:{en:'Read filing',pt:'Ler documento'}, metadata:{en:'Classify & identify',pt:'Classificar e identificar'}, profiler:{en:'Company profile',pt:'Perfil da companhia'}, market:{en:'Market from filing',pt:'Mercado no documento'}, 'market-research':{en:'Cited web peers',pt:'Pares com fontes web'}, risks:{en:'Risk review',pt:'Riscos'}, financials:{en:'Financial analysis',pt:'Análise financeira'}, historian:{en:'Timeline & events',pt:'Linha do tempo'}, synthesizer:{en:'Synthesis',pt:'Síntese'}, dashboard:{en:'Build dashboard',pt:'Montar dashboard'}
};

const sleep=(ms:number)=>new Promise(r=>setTimeout(r,ms));
async function readJson(response:Response){const json=await response.json().catch(()=>({}));if(!response.ok){const error=new Error(String(json.error||`HTTP ${response.status}`)) as Error&{status?:number};error.status=response.status;throw error;}return json;}
async function postJson(url:string,body:unknown,attempts=2){let last:unknown;for(let attempt=1;attempt<=attempts;attempt++){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),105_000);try{return await readJson(await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:controller.signal}));}catch(error){last=error;const status=(error as {status?:number}).status;const transient=(error instanceof DOMException&&error.name==='AbortError')||[408,429,500,502,503,504].includes(status??0);if(!transient||attempt===attempts)throw error;await sleep(900*attempt);}finally{clearTimeout(timer);}}throw last;}

function blankFinancials(): FilingAnalysis['financials'] {return {unit:'',years:[],revenue:[],grossProfit:null,ebit:null,ebitda:null,adjustedEbitda:null,incomeBeforeTax:null,incomeTaxExpense:null,reportedRoic:null,netIncome:[],eps:null,grossMargin:null,operatingMargin:null,operatingCashFlow:null,capex:null,freeCashFlow:null,dividends:null,buybacks:null,totalAssets:null,totalLiabilities:null,totalEquity:null,totalDebt:null,shortTermDebt:null,longTermDebt:null,cash:null,currentAssets:null,currentLiabilities:null,interestExpense:null,accountsReceivable:null,inventory:null,accountsPayable:null,costOfGoodsSold:null,goodwill:null};}
function stageStyle(status:Status){if(status==='running')return 'border-cyan-400/40 bg-cyan-400/10 text-cyan-200';if(status==='complete')return 'border-emerald-400/30 bg-emerald-400/10 text-emerald-200';if(status==='partial')return 'border-amber-400/30 bg-amber-400/10 text-amber-200';if(status==='failed')return 'border-rose-400/30 bg-rose-400/10 text-rose-200';if(status==='skipped')return 'border-slate-700 bg-slate-900/50 text-slate-500';return 'border-slate-800 bg-slate-950/40 text-slate-600';}

export default function Home(){
  const [market,setMarket]=useState<Market>('us'); const [lang,setLang]=useState<Lang>('en'); const [file,setFile]=useState<File|null>(null); const [busy,setBusy]=useState(false); const [configured,setConfigured]=useState<boolean|null>(null); const [error,setError]=useState(''); const [analysis,setAnalysis]=useState<FilingAnalysis|null>(null);
  const [statuses,setStatuses]=useState<Record<StageKey,Status>>(()=>Object.fromEntries(STAGES.map(s=>[s,'pending'])) as Record<StageKey,Status>);
  const t=lang==='pt';
  useEffect(()=>{fetch('/api/status').then(r=>r.json()).then(x=>setConfigured(Boolean(x.configured))).catch(()=>setConfigured(null));},[]);
  const completed=useMemo(()=>STAGES.filter(s=>['complete','partial','skipped'].includes(statuses[s])).length,[statuses]);
  const setStage=(stage:StageKey,status:Status)=>setStatuses(current=>({...current,[stage]:status}));
  const reset=()=>{setAnalysis(null);setError('');setStatuses(Object.fromEntries(STAGES.map(s=>[s,'pending'])) as Record<StageKey,Status>);};

  async function analyze(){
    if(!file||busy)return; reset(); setBusy(true);
    try{
      setStage('extract','running'); const form=new FormData();form.append('file',file);form.append('market',market);const extraction=await readJson(await fetch('/api/extract',{method:'POST',body:form}));setStage('extract','complete');
      const text=String(extraction.text||'');const classification=extraction.classification as FilingClassification;let activeMarket:Market=classification?.jurisdiction??market; if(activeMarket!==market){setMarket(activeMarket);setLang(activeMarket==='br'?'pt':'en');}
      await sleep(350);setStage('metadata','running');const metaRun=await postJson('/api/metadata',{text,classification});setStage('metadata',metaRun.diagnostic?.status==='complete'?'complete':'partial');const metadata=metaRun.result.metadata;
      const results:Record<string,unknown>={};const diagnostics:Record<string,ModuleDiagnostic>={metadata:metaRun.diagnostic};
      for(const agent of AGENTS){
        await sleep(450);setStage(agent,'running');
        try{const run=await postJson('/api/agent',{agent,market:activeMarket,text,filingType:metadata.filingType||classification.filingType,filingDate:metadata.filedAt,priorResults:agent==='synthesizer'?results:undefined});results[agent]=run.result;diagnostics[agent]=run.diagnostic;setStage(agent,run.diagnostic?.status==='complete'?'complete':run.diagnostic?.status==='not_applicable'?'skipped':'partial');
          if(agent==='market'){
            const marketResult=(run.result as {market:{competitors:string[]}}).market;if(marketResult.competitors.length){setStage('market-research','skipped');}else{setStage('market-research','running');try{const research=await postJson('/api/market-research',{market:activeMarket,text,marketResult});results.market=research.result;const d=research.diagnostic as ModuleDiagnostic;diagnostics.market={...diagnostics.market,...d,warnings:[...(diagnostics.market?.warnings??[]),...(d.warnings??[])]};setStage('market-research',research.result.market.externalResearchStatus==='complete'?'complete':research.result.market.externalResearchStatus==='not_needed'?'skipped':'partial');}catch{setStage('market-research','partial');}}
          }
        }catch(agentError){const message=(agentError as Error).message;if(['ai_misconfigured','ai_unavailable','content_rejected'].includes(message))throw agentError;diagnostics[agent]={status:'failed',reason:message};setStage(agent,'failed');if(agent==='market')setStage('market-research','skipped');}
      }
      const profiler=(results.profiler as {company?:FilingAnalysis['company'];kpis?:FilingAnalysis['kpis']})??{};const marketSlice=(results.market as {market?:FilingAnalysis['market']})??{};const risks=(results.risks as {risks?:FilingAnalysis['risks']})??{};const financials=(results.financials as {financials?:FilingAnalysis['financials']})??{};const history=(results.historian as {timeline?:FilingAnalysis['timeline'];events?:FilingAnalysis['events'];validationFlags?:FilingAnalysis['historyValidationFlags']})??{};const synthesis=(results.synthesizer as {summary?:string[];confidenceNotes?:FilingAnalysis['confidenceNotes'];missingData?:string[]})??{};
      const assembled:FilingAnalysis={schemaVersion:'2.0',jurisdiction:activeMarket,metadata,company:profiler.company??{name:t?'Companhia analisada':'Analyzed company',ticker:null,exchange:null,filingType:metadata.filingType||classification.filingType,periodEnd:metadata.reportingPeriod??'',filedAt:metadata.filedAt,filingReference:null,description:t?'Descrição não extraída.':'Description not extracted.'},kpis:profiler.kpis??[],market:marketSlice.market??{industry:'',competitors:[],peerEvidence:[],geographies:[],segments:[],externalResearchStatus:'unavailable'},risks:risks.risks??[],financials:financials.financials??blankFinancials(),timeline:history.timeline??[],events:history.events??[],historyValidationFlags:history.validationFlags,summary:synthesis.summary??[],confidenceNotes:synthesis.confidenceNotes??[],missingData:synthesis.missingData??[],diagnostics};
      setStage('dashboard','running');try{const mapped=await postJson('/api/dashboard-data',{analysis:assembled},1);assembled.prebuiltDashboard=mapped.dashboard;}catch{/* dashboard renders from analysis contract even if prebinding fails */}setAnalysis(assembled);setStage('dashboard','complete');
    }catch(e){setError((e as Error).message||'analysis_failed');}finally{setBusy(false);}
  }

  return <main className="min-h-screen bg-[#060b16] text-slate-100">
    <div className="mx-auto max-w-7xl px-4 py-7 sm:px-6 lg:px-8">
      <header className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-[0.22em] text-cyan-300">FilingLens</div><h1 className="mt-1 text-3xl font-semibold tracking-tight">{t?'Inteligência de filings, com evidência':'Filing intelligence, with evidence'}</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-400">{t?'Analise documentos CVM, valide números e transforme o resultado em dashboard e apresentação profissional.':'Analyze SEC filings, validate the numbers, and turn the result into an interactive dashboard and a professional presentation.'}</p></div><button onClick={()=>setLang(v=>v==='en'?'pt':'en')} className="rounded-lg border border-slate-700 bg-slate-900 px-3 py-2 text-xs text-slate-300">{lang==='en'?'PT-BR':'EN'}</button></header>

      <section className="mb-6 rounded-2xl border border-slate-800 bg-slate-900/60 p-5 shadow-xl shadow-black/20">
        <div className="grid gap-5 lg:grid-cols-[1fr_1.4fr]">
          <div><div className="mb-2 text-xs font-medium text-slate-400">{t?'Mercado / regulador':'Market / regulator'}</div><div className="grid grid-cols-2 gap-2">{([{key:'us',label:'🇺🇸 SEC · United States'},{key:'br',label:'🇧🇷 CVM · Brasil'}] as const).map(option=><button key={option.key} disabled={busy} onClick={()=>{setMarket(option.key);setLang(option.key==='br'?'pt':'en');}} className={`rounded-xl border px-3 py-3 text-sm font-medium ${market===option.key?'border-cyan-500/50 bg-cyan-500/10 text-cyan-200':'border-slate-700 bg-slate-950/50 text-slate-400'}`}>{option.label}</button>)}</div></div>
          <div><div className="mb-2 text-xs font-medium text-slate-400">{t?'Documento regulatório em PDF':'Regulatory filing PDF'}</div><div className="flex flex-col gap-3 sm:flex-row"><label className="flex min-h-12 flex-1 cursor-pointer items-center rounded-xl border border-dashed border-slate-600 bg-slate-950/50 px-4 text-sm text-slate-400 hover:border-cyan-500/50"><input type="file" accept="application/pdf,.pdf" className="hidden" disabled={busy} onChange={e=>setFile(e.target.files?.[0]??null)} /><span className="truncate">{file?.name??(t?'Selecionar PDF (até 20 MB)':'Choose PDF (up to 20 MB)')}</span></label><button onClick={analyze} disabled={!file||busy||configured===false} className="min-h-12 rounded-xl bg-cyan-400 px-5 text-sm font-semibold text-slate-950 disabled:cursor-not-allowed disabled:opacity-40">{busy?(t?'Analisando…':'Analyzing…'):(t?'Iniciar análise':'Start analysis')}</button></div></div>
        </div>
        {configured===false&&<div className="mt-4 rounded-lg border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-xs text-rose-200">OPENAI_API_KEY {t?'não está configurada no servidor.':'is not configured on the server.'}</div>}
        {(busy||completed>0)&&<div className="mt-5"><div className="mb-2 flex items-center justify-between text-xs text-slate-500"><span>{t?'Fluxo de análise':'Analysis workflow'}</span><span>{completed}/{STAGES.length}</span></div><div className="grid gap-2 sm:grid-cols-2 lg:grid-cols-5">{STAGES.map(stage=><div key={stage} className={`rounded-lg border px-3 py-2 ${stageStyle(statuses[stage])}`}><div className="flex items-center justify-between gap-2 text-[11px]"><span>{LABELS[stage][lang]}</span><span className="uppercase opacity-70">{statuses[stage]}</span></div>{statuses[stage]==='running'&&<div className="mt-2 h-1 overflow-hidden rounded bg-slate-800"><div className="h-full w-2/3 animate-pulse rounded bg-cyan-400" /></div>}</div>)}</div></div>}
        {error&&<div className="mt-4 rounded-lg border border-rose-500/30 bg-rose-500/10 px-4 py-3 text-xs text-rose-200">{error}</div>}
      </section>

      {analysis&&<div className="space-y-4"><section className="flex flex-wrap items-center justify-between gap-3 rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4"><div><div className="text-sm font-semibold text-cyan-100">{t?'Análise concluída':'Analysis complete'}</div><div className="mt-1 text-xs text-slate-400">{t?'O deck usa o mesmo objeto validado do dashboard e preserva fontes do documento e da pesquisa web.':'The deck uses the same validated object as the dashboard and preserves filing and web-source provenance.'}</div></div><div className="flex flex-wrap gap-2"><button onClick={()=>downloadCompanyPowerPoint(analysis,lang)} className="rounded-lg bg-cyan-400 px-4 py-2 text-sm font-semibold text-slate-950">{t?'Baixar PowerPoint profissional':'Download professional PowerPoint'}</button><button onClick={()=>{const blob=new Blob([JSON.stringify(analysis,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='filinglens-analysis.json';a.click();URL.revokeObjectURL(a.href);}} className="rounded-lg border border-slate-700 px-4 py-2 text-sm text-slate-300">JSON</button></div></section><Dashboard data={analysis} lang={lang}/></div>}
    </div>
  </main>;
}
