import { useEffect, useMemo, useState } from "react";
import type { CompsValuationResult, DcfValuationResult, FilingAnalysis, ValuationAssumption, ValuationBundle, ValuationMethod, ValuationReconciliation } from "@contracts/analysis";

type Lang="en"|"pt";
type State={assumptions:ValuationAssumption[];result?:DcfValuationResult|CompsValuationResult;loading:boolean;error?:string};
const EMPTY:State={assumptions:[],loading:false};
const L={
 en:{title:"Valuation assumptions",sub:"DCF and trading comps are gated: review assumptions before any valuation number is produced.",prepare:"Prepare assumptions",accept:"Accept",exclude:"Exclude",acceptAll:"Accept populated proposals",calculate:"Calculate validated valuation",pending:"Resolve every proposed assumption first.",dcf:"DCF",comps:"Trading comps",reconcile:"Triangulation",info:"Informational use only — not investment advice.",close:"Hide",open:"Valuation"},
 pt:{title:"Premissas de valuation",sub:"DCF e múltiplos são bloqueados: revise as premissas antes de qualquer valor ser calculado.",prepare:"Preparar premissas",accept:"Aceitar",exclude:"Excluir",acceptAll:"Aceitar propostas preenchidas",calculate:"Calcular valuation validado",pending:"Resolva todas as premissas propostas primeiro.",dcf:"DCF",comps:"Múltiplos",reconcile:"Triangulação",info:"Uso informacional — não constitui recomendação de investimento.",close:"Ocultar",open:"Valuation"},
};

function fmt(v:unknown,d=2){return typeof v==="number"&&Number.isFinite(v)?v.toLocaleString(undefined,{maximumFractionDigits:d}):v===null||v===undefined?"—":String(v)}
function readLang():Lang{return document.documentElement.lang.toLowerCase().startsWith("pt")?"pt":"en"}

export default function ValuationBridge(){
 const [analysis,setAnalysis]=useState<FilingAnalysis|null>(null),[lang,setLang]=useState<Lang>("en"),[open,setOpen]=useState(true),[method,setMethod]=useState<ValuationMethod>("dcf");
 const [dcf,setDcf]=useState<State>(EMPTY),[comps,setComps]=useState<State>(EMPTY),[recon,setRecon]=useState<ValuationReconciliation>();
 const state=method==="dcf"?dcf:comps,setState=method==="dcf"?setDcf:setComps,t=L[lang];
 useEffect(()=>{setLang(readLang()); const observer=new MutationObserver(()=>setLang(readLang())); observer.observe(document.documentElement,{attributes:true,attributeFilter:["lang"]}); return()=>observer.disconnect()},[]);
 useEffect(()=>{const original=window.fetch.bind(window); window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{const url=typeof input==="string"?input:input instanceof URL?input.pathname:input.url; if(url.includes("/api/extract")&&init?.method==="POST"){setAnalysis(null);setDcf(EMPTY);setComps(EMPTY);setRecon(undefined)} if(url.includes("/api/dashboard-data")&&typeof init?.body==="string"){try{const body=JSON.parse(init.body);if(body?.analysis?.company&&body?.analysis?.financials){setAnalysis(body.analysis);setOpen(true)}}catch{}} return original(input,init)}; return()=>{window.fetch=original}},[]);
 useEffect(()=>{if(!dcf.result||!comps.result)return; fetch("/api/valuation/reconcile",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({dcf:dcf.result,comps:comps.result})}).then(r=>r.json()).then(x=>setRecon(x.reconciliation)).catch(()=>{})},[dcf.result,comps.result]);
 const bundle=useMemo<ValuationBundle>(()=>({assumptions:{dcf:dcf.assumptions,comps:comps.assumptions},dcf:dcf.result as DcfValuationResult|undefined,comps:comps.result as CompsValuationResult|undefined,reconciliation:recon}),[dcf,comps,recon]);
 if(!analysis)return null;
 const prepare=async()=>{setState(s=>({...s,loading:true,error:undefined}));try{const r=await fetch("/api/valuation/propose",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({analysis,method})});const b=await r.json();if(!r.ok)throw new Error(b.error||"proposal_failed");setState({assumptions:b.proposal.assumptions,loading:false})}catch(e){setState(s=>({...s,loading:false,error:e instanceof Error?e.message:"proposal_failed"}))}};
 const edit=(id:string,value:string)=>setState(s=>({...s,assumptions:s.assumptions.map(a=>a.id===id?{...a,final_value:value===""?null:Number.isFinite(Number(value))?Number(value):value,status:"edited"}:a)}));
 const accept=(id:string)=>setState(s=>({...s,assumptions:s.assumptions.map(a=>a.id===id?{...a,status:"accepted",final_value:undefined}:a)}));
 const reject=(id:string)=>setState(s=>({...s,assumptions:s.assumptions.map(a=>a.id===id?{...a,status:"rejected"}:a)}));
 const acceptAll=()=>setState(s=>({...s,assumptions:s.assumptions.map(a=>a.status==="proposed"&&a.proposed_value!==null&&a.proposed_value!==""?{...a,status:"accepted"}:a)}));
 const pending=state.assumptions.filter(a=>a.status==="proposed");
 const calculate=async()=>{setState(s=>({...s,loading:true,error:undefined}));try{const r=await fetch("/api/valuation/calculate",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({analysis,method,assumptions:state.assumptions})});const b=await r.json();if(!r.ok)throw new Error(b.pending?.length?`${b.error}: ${b.pending.join(", ")}`:b.error||"calculation_failed");setState(s=>({...s,result:b.result,loading:false}))}catch(e){setState(s=>({...s,loading:false,error:e instanceof Error?e.message:"calculation_failed"}))}};
 const download=()=>{const blob=new Blob([JSON.stringify({company:analysis.company,valuation:bundle},null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`filinglens-valuation-${analysis.company.ticker||analysis.company.name}.json`;a.click();URL.revokeObjectURL(a.href)};
 if(!open)return <button onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-50 rounded-full bg-cyan-500 px-5 py-3 text-xs font-bold text-slate-950 shadow-2xl">{t.open}</button>;
 return <section className="mx-auto mb-16 mt-8 max-w-6xl px-5 sm:px-6">
  <div className="rounded-3xl border border-cyan-500/25 bg-[#0b1220] p-5 text-slate-100 shadow-2xl shadow-slate-950/30 sm:p-6">
   <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="text-[10px] font-bold uppercase tracking-[.18em] text-cyan-300">POST-ANALYSIS · ASSUMPTION GATE</div><h2 className="mt-1 text-xl font-bold">{t.title}</h2><p className="mt-1 max-w-3xl text-xs leading-5 text-slate-400">{t.sub}</p></div><div className="flex gap-2"><button onClick={download} className="rounded-lg border border-slate-700 px-3 py-2 text-[11px]">JSON</button><button onClick={()=>setOpen(false)} className="rounded-lg border border-slate-700 px-3 py-2 text-[11px]">{t.close}</button></div></div>
   <div className="mt-5 flex gap-2">{(["dcf","comps"] as ValuationMethod[]).map(m=><button key={m} onClick={()=>setMethod(m)} className={`rounded-xl px-4 py-2 text-xs font-bold ${method===m?"bg-cyan-500 text-slate-950":"bg-slate-900 text-slate-400"}`}>{m==="dcf"?t.dcf:t.comps}</button>)}</div>
   {!state.assumptions.length?<button disabled={state.loading} onClick={prepare} className="mt-5 rounded-xl bg-blue-600 px-5 py-3 text-xs font-bold disabled:opacity-50">{state.loading?"…":t.prepare}</button>:<>
    <div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="text-[11px] text-slate-500">{pending.length?`${pending.length} pending / pendentes`:"Gate cleared / gate liberado"}</div><button onClick={acceptAll} className="rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-3 py-2 text-[11px] font-semibold text-emerald-200">{t.acceptAll}</button></div>
    <div className="mt-3 overflow-x-auto rounded-2xl border border-slate-800"><table className="min-w-[900px] w-full text-left text-[11px]"><thead className="bg-slate-950/70 text-slate-500"><tr><th className="p-3">Assumption</th><th className="p-3">Value</th><th className="p-3">Confidence</th><th className="p-3">Impact</th><th className="p-3">Rationale / source</th><th className="p-3">Validation</th></tr></thead><tbody>{state.assumptions.map(a=>{const shown=a.status==="edited"?a.final_value:a.proposed_value;return <tr key={a.id} className="border-t border-slate-800 align-top"><td className="p-3"><div className="font-semibold text-slate-200">{a.label}</div><div className="mt-1 text-[9px] text-slate-600">{a.id}</div></td><td className="p-3"><input value={shown===null||shown===undefined?"":String(shown)} onChange={e=>edit(a.id,e.target.value)} className="w-32 rounded-lg border border-slate-700 bg-slate-950 px-2 py-1.5 text-slate-200"/><span className="ml-1 text-slate-600">{a.unit}</span></td><td className="p-3">{a.confidence}</td><td className="p-3">{a.impact}</td><td className="max-w-xs p-3 text-slate-400">{a.rationale}{a.source?.url&&<a href={a.source.url} target="_blank" rel="noreferrer" className="mt-1 block text-cyan-400 underline">{a.source.publisher||"source"}</a>}</td><td className="p-3"><div className="flex gap-1"><button disabled={shown===null||shown===""} onClick={()=>accept(a.id)} className="rounded bg-emerald-500/15 px-2 py-1 text-emerald-300 disabled:opacity-30">{t.accept}</button>{a.category==="peer_multiple"&&<button onClick={()=>reject(a.id)} className="rounded bg-slate-700 px-2 py-1 text-slate-300">{t.exclude}</button>}</div><div className="mt-1 text-[9px] text-slate-600">{a.status}</div></td></tr>})}</tbody></table></div>
    {pending.length>0&&<p className="mt-3 text-xs text-amber-300">{t.pending}</p>}<button disabled={state.loading||pending.length>0} onClick={calculate} className="mt-4 rounded-xl bg-emerald-600 px-5 py-3 text-xs font-bold disabled:opacity-40">{state.loading?"…":t.calculate}</button>
   </>}
   {state.error&&<div className="mt-4 rounded-xl border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-200">{state.error}</div>}
   {state.result&&<Result result={state.result}/>} {recon&&<div className={`mt-5 rounded-2xl border p-4 ${recon.status==="divergent"?"border-amber-500/40 bg-amber-500/5":"border-cyan-500/30 bg-cyan-500/5"}`}><h3 className="text-sm font-bold">{t.reconcile} · {recon.status}</h3><p className="mt-2 text-xs text-slate-400">DCF {fmt(recon.dcf_per_share)} · Comps {fmt(recon.comps_per_share)} · Δ {fmt(recon.divergence_percent)}%</p>{recon.notes.map(n=><p key={n} className="mt-1 text-[11px] text-slate-500">{n}</p>)}</div>}
   <p className="mt-5 text-[10px] text-slate-600">{t.info}</p>
  </div>
 </section>;
}

function Result({result}:{result:DcfValuationResult|CompsValuationResult}){
 if(result.method==="dcf")return <div className="mt-6"><div className="grid gap-3 sm:grid-cols-4">{[["EV",result.figures.enterprise_value],["Equity",result.figures.equity_value],["Per share",result.figures.implied_per_share],["WACC",result.figures.wacc]].map(([k,v]:any)=><div key={k} className="rounded-xl border border-slate-800 bg-slate-950/50 p-3"><div className="text-[10px] text-slate-500">{k}</div><div className="mt-1 text-lg font-bold">{fmt(v.value)} <span className="text-xs text-slate-500">{v.unit}</span></div></div>)}</div><div className="mt-4 overflow-x-auto"><table className="min-w-[650px] w-full text-[11px]"><thead><tr className="text-slate-500"><th>Year</th><th>Revenue</th><th>EBIT margin</th><th>FCFF</th></tr></thead><tbody>{result.projections.map(p=><tr key={p.year} className="border-t border-slate-800 text-center"><td className="p-2">{p.year}</td><td>{fmt(p.revenue)}</td><td>{fmt(p.ebit_margin)}%</td><td>{fmt(p.fcff)}</td></tr>)}</tbody></table></div><h4 className="mt-4 text-xs font-bold">WACC × terminal growth sensitivity</h4><div className="mt-2 overflow-x-auto"><table className="text-[10px]"><tbody>{result.sensitivity.values.map((row,i)=><tr key={i}><th className="p-2 text-slate-500">{result.sensitivity.wacc[i]}%</th>{row.map((v,j)=><td key={j} className="border border-slate-800 p-2">{fmt(v)}</td>)}</tr>)}</tbody></table></div><div className="mt-4 flex gap-3 text-xs"><span>Bull {fmt(result.scenarios.bull.value)}</span><span>Base {fmt(result.scenarios.base.value)}</span><span>Bear {fmt(result.scenarios.bear.value)}</span></div></div>;
 return <div className="mt-6"><div className="grid gap-3 sm:grid-cols-4">{[["Selected multiple",result.figures.selected_multiple],["EV",result.figures.enterprise_value],["Equity",result.figures.equity_value],["Per share",result.figures.implied_per_share]].map(([k,v]:any)=><div key={k} className="rounded-xl border border-slate-800 bg-slate-950/50 p-3"><div className="text-[10px] text-slate-500">{k}</div><div className="mt-1 text-lg font-bold">{fmt(v.value)} <span className="text-xs text-slate-500">{v.unit}</span></div></div>)}</div><p className="mt-4 text-xs text-slate-400">{result.multiple_metric} · Q1 {fmt(result.quartiles.q1.value)}x · Median {fmt(result.quartiles.median.value)}x · Q3 {fmt(result.quartiles.q3.value)}x</p><div className="mt-3 flex flex-wrap gap-2">{result.peers.map(p=><span key={p.assumption_id} className="rounded-lg border border-slate-800 px-3 py-2 text-[11px]">{p.name}: {fmt(p.multiple)}x</span>)}</div></div>;
}
