import type { z } from "zod";
import { companySchema, financialsSchema, historySchema, marketSchema, metadataSchema, risksSchema, summarySchema, type AgentName, type FilingClassification, type FinancialsResult, type MetadataResult, type Market } from "../contracts/analysis";
import { buildAgentInput, buildMetadataInput, runAgent, runMetadataAgent } from "./analyze";
import { assessCompleteness, assessMetadataCompleteness } from "./completeness";
import { applyFinancialValidation } from "./financial-validation";
import { validateHistorianOutput } from "./historian-validation";
import { validateMarketOutput } from "./market-validation";
import { extractDatedFilingEvents } from "./timeline-skill-extraction";
const AGENT_SCHEMAS={profiler:companySchema,market:marketSchema,risks:risksSchema,financials:financialsSchema,historian:historySchema,synthesizer:summarySchema} as const;
export const MANAGED_AGENT_ORDER:AgentName[]=["profiler","market","risks","financials","historian","synthesizer"];
type ManagedRun={result:unknown;diagnostic:ReturnType<typeof assessCompleteness>;manager:{stage:number;totalStages:number;agent:AgentName;excerptChars:number;attempts:number;subtools:string[]};evaluation:{schemaValid:true;completeness:ReturnType<typeof assessCompleteness>["status"]}};
export function synthesisInput(excerpt:string,priorResults?:Record<string,unknown>):string{if(!priorResults)return excerpt;const allowed=Object.fromEntries(["profiler","market","risks","financials","historian"].filter(key=>Object.hasOwn(priorResults,key)).map(key=>[key,priorResults[key]]));return `${excerpt}\n\n[Earlier specialist outputs; summarize filing-supported facts only and identify gaps]\n${JSON.stringify(allowed).slice(0,24000)}`;}
export const agentManager={
  plan(){return{manager:"FilingLens Agent Manager",schemaVersion:"2.0",metadataStage:"metadata",agents:MANAGED_AGENT_ORDER,dashboardStage:"prebuilt-dashboard-mapping",retryBoundary:"client-owned-per-stage",marketResearchStage:"separate-cited-web-fallback",integrations:[{skill:"equity-research",stage:"profiler",integration:"prompt_method_only",mode:"filing identity checks"},{skill:"market-research-brief",stage:"market",integration:"filing_then_separate_cited_web_search",mode:"web fallback only when filing names no peers"},{skill:"financial-ratio-toolkit",stage:"financials",integration:"typescript_calculation",mode:"filing-only ratios"},{skill:"financial-statement-analyzer",stage:"financials",integration:"typescript_calculation",mode:"trend and anomaly screens"},{skill:"filing-timeline-extractor",stage:"historian",integration:"typescript_validation",mode:"filing-only events"}]};},
  async runMetadata(market:Market,filingText:string,classification:FilingClassification){const excerpt=buildMetadataInput(filingText);const result=await runMetadataAgent(market,excerpt,metadataSchema) as MetadataResult;result.metadata.jurisdiction=classification.jurisdiction;if(!result.metadata.filingType)result.metadata.filingType=classification.filingType;result.metadata.confidence=Math.min(result.metadata.confidence,classification.confidence);const diagnostic=assessMetadataCompleteness(result);return{result,diagnostic,manager:{stage:0,totalStages:MANAGED_AGENT_ORDER.length+1,agent:"metadata" as const,excerptChars:excerpt.length,attempts:1},evaluation:{schemaValid:true as const,completeness:diagnostic.status}};},
  async run(agent:AgentName,market:Market,filingText:string,context:{jurisdiction:Market;filingType:string;filingDate?:string|null;priorResults?:Record<string,unknown>}):Promise<ManagedRun>{const schema:z.ZodTypeAny=AGENT_SCHEMAS[agent];const excerpt=buildAgentInput(agent,filingText);const input=agent==="synthesizer"?synthesisInput(excerpt,context.priorResults):excerpt;const managedValue=await runAgent(agent,market,input,schema,context);const subtools:string[]=[];let result=managedValue;
    if(agent==="financials"){result=applyFinancialValidation(managedValue as FinancialsResult);subtools.push("financial-ratio-toolkit","financial-statement-analyzer");}
    if(agent==="historian"){const history=managedValue as import("../contracts/analysis").HistoryResult;const validated=validateHistorianOutput(history,context.filingDate);if(!validated.timeline.length&&!validated.events.length){const fallback=extractDatedFilingEvents(excerpt);result=validateHistorianOutput({...history,events:fallback},context.filingDate);}else result=validated;subtools.push("filing-timeline-extractor","filing-timeline-extractor-validator");}
    if(agent==="market"){const marketResult=validateMarketOutput(managedValue as import("../contracts/analysis").MarketResult);if(marketResult.market.competitors.length>0)marketResult.market.externalResearchStatus="not_needed";result=marketResult;subtools.push("filing-source-provenance-validator","market-research-brief-period-comparison");}
    if(agent==="profiler")subtools.push("equity-research-tear-sheet-method");if(agent==="market")subtools.push("market-research-brief-analysis-framework");const diagnostic=assessCompleteness(agent,result,context);
    if(["profiler","historian"].includes(agent)){diagnostic.enrichmentStatus="skipped";diagnostic.warnings=["external_enrichment_unavailable"];}
    if(agent==="historian"){const history=result as import("../contracts/analysis").HistoryResult;if((history.validationFlags?.length??0)>0)diagnostic.warnings=[...(diagnostic.warnings??[]),"historian_validation_flags"];}
    if(agent==="market"){const marketResult=result as import("../contracts/analysis").MarketResult;const researchStatus=marketResult.market.externalResearchStatus;diagnostic.enrichmentStatus=researchStatus==="not_needed"?"none":"skipped";if(!researchStatus)diagnostic.warnings=["external_market_research_pending"];if((marketResult.market.validationFlags?.length??0)>0)diagnostic.warnings=[...(diagnostic.warnings??[]),"market_validation_flags"];}
    const stage=MANAGED_AGENT_ORDER.indexOf(agent)+1;return{result,diagnostic,manager:{stage,totalStages:MANAGED_AGENT_ORDER.length+1,agent,excerptChars:excerpt.length,attempts:1,subtools},evaluation:{schemaValid:true,completeness:diagnostic.status}};
  }
};
