import { generateObject, type LanguageModel } from "ai";
import type { z } from "zod";
import pdfParse from "./pdf";
import { filingModel } from "./ai/provider";
import { AiMisconfigured, classifyAiError } from "./lib/ai-client";
import { AGENTS, METADATA_AGENT, type AgentName } from "./engines";
import type { Jurisdiction, Market } from "../contracts/analysis";

const MAX_TEXT_CHARS = 220_000;
const AGENT_TIMEOUT_MS = 95 * 1000;
const BR_FINANCIAL_HEADINGS = [/demonstra(?:ç|c)(?:ão|ao)\s+(?:do|de)\s+resultado(?:\s+do\s+exerc[ií]cio)?/i,/balan(?:ç|c)o\s+patrimonial/i,/demonstra(?:ç|c)(?:ão|ao)\s+dos?\s+fluxos?\s+de\s+caixa/i,/demonstra(?:ç|c)(?:ão|ao)\s+das?\s+muta(?:ç|c)(?:ões|oes)\s+do\s+patrim[oô]nio\s+l[ií]quido/i,/informa(?:ç|c)(?:ões|oes)\s+financeiras\s+selecionadas/i,/informa(?:ç|c)(?:ões|oes)\s+por\s+segmento/i];
const BR_RISK_HEADINGS = [/fatores\s+de\s+risco/i,/principais\s+riscos/i,/gest[aã]o\s+de\s+riscos/i];
const BR_MARKET_HEADINGS = [/segmentos?\s+(?:operacionais|de\s+neg[oó]cios)/i,/informa(?:ç|c)(?:ões|oes)\s+por\s+segmento/i,/concorr(?:e|ê)ncia|concorrentes/i,/(?:vis[aã]o\s+geral\s+do\s+)?mercado\s+(?:de|e|em|no|na)\s+(?:atua(?:ç|c)(?:ão|ao)|opera(?:ç|c)(?:ão|ao)|neg[oó]cios|combust[ií]veis|lubrificantes)/i,/ambiente\s+(?:de\s+)?neg[oó]cios/i,/ambiente\s+concorrencial/i,/setor\s+de\s+atua(?:ç|c)(?:ão|ao)/i,/principais\s+mercados/i,/participa(?:ç|c)(?:ão|ao)\s+(?:de\s+)?mercado/i];
const SEC_SECTION_HEADINGS = [/item\s+1\.?\s+business/i,/item\s+1a\.?\s+risk\s+factors/i,/item\s+7\.?\s+management'?s\s+discussion/i,/item\s+8\.?\s+financial\s+statements/i,/item\s+2\.?\s+management'?s\s+discussion/i];
const EVENT_HEADINGS = [/fato\s+relevante/i,/eventos?\s+subsequentes?/i,/item\s+[125]\.0[1258]/i,/current\s+report\s+on\s+form\s+8-k/i];
export class BadFiling extends Error { constructor(message: string) { super(message); this.name = "BadFiling"; } }
export async function extractFilingText(buf: Buffer): Promise<string> { let text: string; try { const data = await pdfParse(buf); text = (data.text || "").replace(/[ \t]+\n/g, "\n").replace(/\n{3,}/g, "\n\n").trim(); } catch { throw new BadFiling("unreadable_pdf"); } if (text.length < 2000) throw new BadFiling("too_little_text"); return createAnalysisCorpus(text); }
function findSectionStart(text: string, patterns: RegExp[]): number { for (const re of patterns) { const m = re.exec(text); if (m) return m.index; } return -1; }
function sliceSection(text: string, startPatterns: RegExp[], endPatterns: RegExp[], maxChars: number): string { const start = findSectionStart(text, startPatterns); if (start < 0) return ""; let end = -1; for (const re of endPatterns) { re.lastIndex = 0; const m = re.exec(text.slice(start + 50)); if (m && (end < 0 || start + 50 + m.index < end)) end = start + 50 + m.index; } const stop = end > start ? Math.min(end, start + maxChars) : start + maxChars; return text.slice(start, stop); }
function headingWindows(text: string, patterns: RegExp[], windowChars: number, maxWindows = 6): string[] { const starts: number[] = []; for (const pattern of patterns) { const flags = pattern.flags.includes("g") ? pattern.flags : `${pattern.flags}g`; const re = new RegExp(pattern.source, flags); for (const match of text.matchAll(re)) starts.push(match.index ?? 0); } starts.sort((a,b)=>a-b); const distinct = starts.filter((start,index)=>index===0 || start-starts[index-1] > 2000); return distinct.slice(0,maxWindows).map(start=>text.slice(start,start+windowChars)); }
function createAnalysisCorpus(text: string): string { if (text.length <= MAX_TEXT_CHARS) return text; const sections=[text.slice(0,32000)]; const prioritized=[...headingWindows(text,BR_FINANCIAL_HEADINGS,30000),...headingWindows(text,BR_RISK_HEADINGS,26000),...headingWindows(text,BR_MARKET_HEADINGS,22000),...headingWindows(text,SEC_SECTION_HEADINGS,26000),...headingWindows(text,EVENT_HEADINGS,18000,4)]; for (const section of prioritized) { const candidate=`${sections.join("\n\n[... filing section ...]\n\n")}\n\n[... filing section ...]\n\n${section}`; if (candidate.length>MAX_TEXT_CHARS) break; sections.push(section); } return `${sections.join("\n\n[... filing section ...]\n\n")}\n\n[... filing text selectively condensed for analysis ...]`; }
export function buildAgentInput(agent: AgentName, text: string): string {
  const lower=text.toLowerCase();
  const business=sliceSection(text,[/item\s+1\.?\s+business(?!\s*\d)/i,/item\s+1\.\s+descri(?!\s*\d)/i,/descri(?:ç|c)(?:ão|ao)\s+(?:das?\s+)?atividades/i],[/item\s+1a/i,/item\s+2\.?\s+propert/i,/item\s+1b/i],40000);
  const risks=sliceSection(text,[/item\s+1a(?!\s*\d)/i,...BR_RISK_HEADINGS],[/item\s+2\.?\s+unregistered/i,/item\s+2\.?\s+propert/i,/item\s+1b/i,/controles?\s+internos?/i],70000);
  const mdna=sliceSection(text,[/item\s+[27]\.?\s+management'?s\s+discussion(?!\s*\d)/i,/item\s+7\.\s+coment/i,/coment[aá]rio\s+da\s+administra(?:ç|c)(?:ão|ao)/i,/an[aá]lise\s+e\s+discuss[aã]o\s+da\s+administra(?:ç|c)(?:ão|ao)/i],[/item\s+[38]\.?\s+(quantitative|financial)/i,/item\s+4\.?\s+controls/i],40000);
  const statements=sliceSection(text,[/item\s+1\.?\s+financial\s+statements(?!\s*\d)/i,/item\s+8\.?\s+financial(?!\s*\d)/i,/demonstra(?:ç|c)(?:ões|oes)\s+financeiras/i,...BR_FINANCIAL_HEADINGS],[/item\s+[23]\.?\s+management/i,/item\s+9/i,/notas?\s+explicativas?/i],40000);
  const head=text.slice(0,45000); const i=Math.max(lower.indexOf("risk factors"),lower.indexOf("fatores de risco")); const riskFallback=i<0?"":text.slice(i,i+70000); const brFinancials=headingWindows(text,BR_FINANCIAL_HEADINGS,18000,5); const brMarket=headingWindows(text,BR_MARKET_HEADINGS,16000,3); let out="";
  switch(agent){case "profiler":out=(business||head).slice(0,45000);break;case "market":out=[business,mdna,...brMarket,business||head].filter((s,index,a)=>Boolean(s)&&a.indexOf(s)===index).join("\n\n[... market disclosure ...]\n\n").slice(0,55000);break;case "risks":out=(risks||riskFallback||head).slice(0,70000);break;case "financials":out=[mdna,statements,...brFinancials].filter(Boolean).join("\n\n[... financial statements ...]\n\n").slice(0,90000);if(!statements&&!brFinancials.length)out=(mdna||head).slice(0,75000);break;case "historian":out=[business.slice(0,24000)||head.slice(0,24000),mdna.slice(0,18000),...headingWindows(text,EVENT_HEADINGS,15000,4)].filter(Boolean).join("\n\n[... later sections ...]\n\n").slice(0,70000);break;case "synthesizer":out=[text.slice(0,12000),mdna.slice(0,30000)].filter(Boolean).join("\n\n[... management discussion ...]\n\n").slice(0,40000);break;} if(out.length<2000)out=text.slice(0,60000);if(out.length<2000)out=text;return out;
}
export function buildMetadataInput(text:string):string{return text.slice(0,50000)}
const modelCache=new Map<string,LanguageModel>(); async function model(stage:AgentName|"metadata"):Promise<LanguageModel>{if(!process.env.OPENAI_API_KEY)throw new AiMisconfigured("OPENAI_API_KEY is not configured");const cached=modelCache.get(stage);if(cached)return cached;const selected=filingModel(stage);modelCache.set(stage,selected);return selected;}
export async function runAgent(agent:AgentName,market:Market,text:string,schema:z.ZodTypeAny,context?:{jurisdiction:Jurisdiction;filingType:string}):Promise<any>{try{const contextPrompt=context?`\n## Confirmed filing context\n- Jurisdiction: ${context.jurisdiction}\n- Filing type: ${context.filingType}\nApply the matching regulator and filing-type contract.\n`:"";const res=await generateObject({model:await model(agent),schema,system:AGENTS[agent].system(market)+contextPrompt,messages:[{role:"user",content:text}],providerOptions:{openai:{maxCompletionTokens:AGENTS[agent].maxTokens}},maxRetries:0,abortSignal:AbortSignal.timeout(AGENT_TIMEOUT_MS)});return res.object;}catch(err){throw classifyAiError(err)}}
export async function runMetadataAgent(market:Market,text:string,schema:z.ZodTypeAny):Promise<any>{try{const res=await generateObject({model:await model("metadata"),schema,system:METADATA_AGENT.system(market),messages:[{role:"user",content:buildMetadataInput(text)}],providerOptions:{openai:{maxCompletionTokens:METADATA_AGENT.maxTokens}},maxRetries:0,abortSignal:AbortSignal.timeout(AGENT_TIMEOUT_MS)});return res.object;}catch(err){throw classifyAiError(err)}}
