import type { Market } from '../contracts/analysis';
const common = `Return ONLY schema-valid JSON. Use English for US and PT-BR for Brazil. Use filing facts only unless the calling stage explicitly supplies cited web evidence. Monetary values are numeric millions in filing currency. Keep periods comparable and oldest-to-newest. Never invent identifiers, figures, dates, peers, pages, or citations. Use null/empty arrays when absent. Attach the nearest filing section and exact short quote to material claims where the schema permits.`;
const language = (market: Market, en: string, pt: string) => `${market === 'br' ? pt : en}\n${common}`;
export const METADATA_AGENT = { maxTokens: 1400, system: (m: Market) => language(m, 'Extract SEC filing metadata: form, period, filed date, CIK, SIC, fiscal year end, state of incorporation and source references. jurisdiction=us.', 'Extraia metadados CVM: classe do documento, período, data de entrega, CNPJ, dados cadastrais e referências. jurisdiction=br.') };
export const AGENTS = {
  profiler: { maxTokens: 2500, system: (m: Market) => language(m, 'Extract issuer identity, business description and 5-8 latest-period filing-supported KPIs with sources. No valuation, rating, price target, catalysts or outside research.', 'Extraia identidade, descrição do negócio e 5-8 KPIs do período mais recente, todos sustentados pelo documento. Não inclua valuation, recomendação, preço-alvo, catalisadores ou pesquisa externa.') },
  market: { maxTokens: 2200, system: (m: Market) => language(m, 'Extract industry, filing-named competitors, geographic revenue and operating segments. Every competitor must have filing peerEvidence with an exact quote. Every geography/segment must have aligned periods and filing source. Do not use memory for market size/share.', 'Extraia setor, concorrentes citados, receita geográfica e segmentos operacionais. Todo concorrente deve ter peerEvidence do documento com citação exata. Geografias/segmentos devem ter períodos alinhados e fonte do documento. Não use memória para tamanho/participação de mercado.') },
  risks: { maxTokens: 2500, system: (m: Market) => language(m, 'Extract 5-10 material risks, category, severity 1-5, materiality rank, concise summary and filing source.', 'Extraia 5-10 riscos materiais, categoria, gravidade 1-5, ranking de materialidade, resumo e fonte do documento.') },
  financials: { maxTokens: 3200, system: (m: Market) => language(m, 'Extract up to five comparable financial periods and reported revenue, gross profit, COGS, EBIT, EBITDA/Adjusted EBITDA separately, pretax/tax, net income, EPS, margins, OCF, capex, FCF, dividends/buybacks, assets/liabilities/equity, debt, cash, working-capital lines, interest, goodwill, evidence and guidance. Never mix quarter/YTD/FY.', 'Extraia até cinco períodos comparáveis e receita, lucro bruto, CPV/CSP, EBIT, EBITDA/EBITDA Ajustado separadamente, pré-impostos/tributos, lucro líquido, LPA, margens, FCO, capex, FCL, dividendos/recompras, ativo/passivo/PL, dívida, caixa, capital de giro, juros, goodwill, evidências e guidance. Nunca misture trimestre/acumulado/exercício.') },
  historian: { maxTokens: 3600, system: (m: Market) => language(m, 'Extract filing-only corporate milestones and events with explicit date granularity, category, materiality, exact excerpt and section. Do not fabricate missing day/month or external events.', 'Extraia marcos e eventos apenas do documento, com granularidade explícita da data, categoria, materialidade, citação exata e seção. Não complete dia/mês ausente nem crie eventos externos.') },
  synthesizer: { maxTokens: 1600, system: (m: Market) => language(m, 'Using the specialist outputs plus excerpt, produce up to six concise evidence-supported summary bullets, confidence notes and missing-data inventory. Never upgrade an incomplete module into a fact.', 'Com base nos especialistas e no trecho, produza até seis tópicos concisos sustentados por evidência, notas de confiança e inventário de dados ausentes. Nunca transforme módulo incompleto em fato.') },
} as const;
export type AgentName = keyof typeof AGENTS;
