import { generateText, Output, stepCountIs } from "ai";
import { z } from "zod";
import type { MarketResult } from "../contracts/analysis";
import { filingModel, marketWebSearchTool } from "./ai/provider";
const webResearchOutput=z.object({peers:z.array(z.object({name:z.string().min(1).max(100),url:z.string().url(),reason:z.string().min(1).max(240)})).max(8)});
type ResearchPeer=z.infer<typeof webResearchOutput>["peers"][number];
function canonicalUrl(value:string):string|null{try{const url=new URL(value);if(url.protocol!=="https:")return null;url.hash="";url.search="";return `${url.origin}${url.pathname.replace(/\/$/,"")}`.toLowerCase();}catch{return null}}
export function verifyMarketResearchPeers(peers:ResearchPeer[],sources:Array<{url:string;title?:string}>,accessed=new Date().toISOString().slice(0,10)):NonNullable<MarketResult["market"]["peerEvidence"]>{const citedSources=new Map<string,{url:string;title?:string}>();for(const source of sources){const key=canonicalUrl(source.url);if(key)citedSources.set(key,source)}const seen=new Set<string>();const verified:NonNullable<MarketResult["market"]["peerEvidence"]>=[];for(const peer of peers){const name=peer.name.trim(),key=canonicalUrl(peer.url);if(!name||!key||seen.has(name.toLowerCase()))continue;const cited=citedSources.get(key);if(!cited)continue;let publisher=cited.title?.trim();try{publisher ||= new URL(cited.url).hostname.replace(/^www\./,"")}catch{continue}seen.add(name.toLowerCase());verified.push({name,sourceType:"external",source:{section:"Independent web research",kind:"citation",url:cited.url,publisher,accessed}});if(verified.length===8)break}return verified;}
export async function researchMarketPeers(input:{jurisdiction:"us"|"br";industry:string;filingExcerpt:string}):Promise<NonNullable<MarketResult["market"]["peerEvidence"]>>{const result=await generateText({model:filingModel("market"),output:Output.object({schema:webResearchOutput}),tools:{web_search:marketWebSearchTool() as never},stopWhen:stepCountIs(3),maxRetries:0,maxOutputTokens:2000,abortSignal:AbortSignal.timeout(90000),system:["You are a cautious public-equity industry researcher. The uploaded filing is authoritative for issuer identity and disclosed facts.","Use web search now; do not answer from memory. Find current direct competitors only.","Prefer official company pages, regulatory filings and credible industry sources.","Return peers only when the exact supporting URL appears in web-search citations. If ambiguous, return an empty list.","Do not add financial figures, market shares, valuation or recommendations."].join(" "),prompt:`Jurisdiction: ${input.jurisdiction === "br" ? "Brazil / CVM" : "United States / SEC"}\nIndustry: ${input.industry || "not identified"}\n\nFiling excerpt:\n${input.filingExcerpt.slice(0,18000)}\n\nFind up to 8 direct competitors and return the exact cited URL.`});return verifyMarketResearchPeers(result.output.peers,result.sources.filter(source=>source.sourceType==="url").map(source=>({url:source.url,title:source.title})));}
