import {describe,it,expect} from "vitest";
import {citedUrls} from "./market-web-research";
describe("web-search citation provenance",()=>{
 it("includes URLs supplied by provider search tool results when top-level sources are absent",()=>{
  const refs=citedUrls({sources:[],steps:[{
   sources:[],toolResults:[{toolName:"web_search",output:{sources:[
    {type:"url",url:"https://www.sec.gov/Archives/edgar/data/123/filing",title:"SEC filing"},
   ]}}],
  }]});
  expect(refs).toEqual([{url:"https://www.sec.gov/Archives/edgar/data/123/filing",title:"SEC filing"}]);
 });
 it("rejects uncited URLs generated by the model and drops repeated URLs",()=>{
  const refs=citedUrls({sources:[{sourceType:"url",url:"https://example.com/1"}],
    steps:[{sources:[{sourceType:"url",url:"https://example.com/1"}],
      toolResults:[{toolName:"untrusted_model",output:{sources:[{url:"https://invented.example/"}]}}]}]});
  expect(refs).toHaveLength(1);
 });
});
