import { describe, expect, it } from "vitest";
import type { FilingAnalysis, ValuationAssumption } from "../contracts/analysis";
import { calculateValuation, reconcileValuations, ValuationGateError } from "./valuation-manager";

const analysis:FilingAnalysis={schemaVersion:"2.0",jurisdiction:"us",metadata:{jurisdiction:"us",filingType:"10-K",reportingPeriod:"2025",filedAt:null,confidence:1,cnpj:null,cvmDocumentClass:null,registryData:null,cik:"1",sicCode:null,fiscalYearEnd:null,stateOfIncorporation:null,sources:[]},company:{name:"Test Co",ticker:"TST",exchange:"NYSE",filingType:"10-K",periodEnd:"2025",filedAt:null,description:"test"},kpis:[],market:{industry:"Software",competitors:["A","B","C"],geographies:[],segments:[]},risks:[],financials:{unit:"USD millions",years:["2024","2025"],revenue:[300,360],ebit:[30,36],ebitda:[36,43.2],incomeBeforeTax:[27,32],incomeTaxExpense:[5.4,6.4],netIncome:[22,24],eps:[2.2,2.4],grossMargin:null,operatingMargin:[.1,.1],operatingCashFlow:[40,45],capex:[-12,-14.4],freeCashFlow:[28,30.6],dividends:null,buybacks:null,totalAssets:[500,550],totalDebt:[80,90],cash:[25,30],currentAssets:[150,165],currentLiabilities:[100,110],interestExpense:[4,4.5],accountsReceivable:[60,72],inventory:[12,14],accountsPayable:[30,36]},timeline:[],events:[],summary:[],confidenceNotes:[],missingData:[]};
const a=(id:string,value:number|string,status:ValuationAssumption["status"]="accepted"):ValuationAssumption=>({id,method:"dcf",category:"test",label:id,proposed_value:value,rationale:"test",confidence:"high",impact:"high",status});

describe("valuation assumption gate",()=>{
 it("blocks DCF while assumptions are proposed",()=>{expect(()=>calculateValuation(analysis,"dcf",[a("x",1,"proposed")])).toThrow(ValuationGateError)});
 it("calculates comps quartiles and per-share after validation",()=>{const base=(id:string,value:number|string,category="framework"):ValuationAssumption=>({id,method:"comps",category,label:id,proposed_value:value,rationale:"test",confidence:"high",impact:"high",status:"accepted"});const rows=[base("comps.multiple_metric","EV/EBITDA"),base("comps.selected_multiple",8),base("comps.target_metric",36),base("comps.net_debt",60),base("comps.shares_outstanding",10),base("p1",7,"peer_multiple"),base("p2",8,"peer_multiple"),base("p3",9,"peer_multiple")];const r=calculateValuation(analysis,"comps",rows);if(r.method!=="comps")throw new Error();expect(r.quartiles.q1.value).toBe(7.5);expect(r.quartiles.median.value).toBe(8);expect(r.quartiles.q3.value).toBe(8.5);expect(r.figures.enterprise_value.value).toBe(288);expect(r.figures.equity_value.value).toBe(228);expect(r.figures.implied_per_share.value).toBe(22.8)});
 it("marks reconciliation unavailable until both methods exist",()=>{expect(reconcileValuations(undefined,undefined).status).toBe("unavailable")});
});
